# ***Forecast Volumen de créditos generales***

In [1]:
# Manejo de datos
import os # Directorios
import pandas as pd # Manipulación df
# Gráficas
import plotly.graph_objects as go #Para obtener librería usar: pip install plotly
from plotly.subplots import make_subplots
import plotly.io as pio # Exportar gráfica

In [2]:
# Obtener el directorio actual de trabajo
directorio_actual = os.getcwd()
# Directorio donde se encuentran los archivos JSON (ruta relativa)
directorio_json = os.path.join(directorio_actual, 'datos_json')
#print("Directorio JSON relativo:", directorio_json)
# Obtener la lista de archivos JSON en el directorio
archivos_json = os.listdir(directorio_json)

In [3]:
dataframes = {} # Crear un diccionario para almacenar los DataFrames
# Iterar sobre cada archivo JSON y crear un DataFrame
for archivo in archivos_json:
    # Obtener el nombre de la tabla del nombre del archivo
    nombre_tabla = archivo.replace('datos_', '').replace('.json', '')    
    # Cargar el archivo JSON en un DataFrame y asignarlo a una variable con un nombre dinámico
    ruta_json = os.path.join(directorio_json, archivo)
    globals()[f"df_{nombre_tabla}"] = pd.read_json(ruta_json)

In [4]:
# Obtener todos los nombres de las variables globales
nombres_variables_globales = list(globals().keys())
# Filtrar los nombres para obtener solo aquellos que comienzan con "df_"
nombres_df = [nombre for nombre in nombres_variables_globales if nombre.startswith("df_")]
# Imprimir la lista de nombres de los DataFrames creados
print("Lista de DataFrames creados:")
print(nombres_df)

Lista de DataFrames creados:
['df_alfa_q_feb_2023_pachuca', 'df_alfa_q_jul_2023_pachuca', 'df_alfa_q_jun_2023_pachuca', 'df_alfa_q_mar_2023_pachuca', 'df_alfa_q_nov_2022_pachuca', 'df_alfa_q_oct_2022_pachuca', 'df_alfa_q_sep_2023_pachuca', 'df_enero_2024_querertaro', 'df_financiamientos_2019_pachuca', 'df_financiamientos_2020_pachuca', 'df_financiamientos_2021_pachuca', 'df_financiamientos_2022_pachuca', 'df_financiamientos_2023_pachuca', 'df_grupos_edad_pachuca', 'df_grupos_edad_queretaro', 'df_junio_2023_queretaro', 'df_salarios_pachuca', 'df_usuarios']

____
## ***TOTAL***

In [5]:
creditos_2019_pachuca = df_financiamientos_2019_pachuca[['id','año','mes','modalidad','monto']]
creditos_2020_pachuca = df_financiamientos_2020_pachuca[['id','año','mes','modalidad','monto']]
creditos_2021_pachuca = df_financiamientos_2021_pachuca[['id','año','mes','modalidad','monto']]
creditos_2022_pachuca = df_financiamientos_2022_pachuca[['id','año','mes','modalidad','monto']]
creditos_2023_pachuca = df_financiamientos_2023_pachuca[['id','año','mes','modalidad','monto']]

## *Todos*

In [6]:
total_creditos_2019_pachuca = creditos_2019_pachuca.groupby('mes')['monto'].sum().reset_index()
total_creditos_2019_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
# Calcular la variación porcentual
#total_creditos_2019_pachuca['var_porcentual'] = total_creditos_2019_pachuca['montos'].pct_change() * 100
# Asignar el valor '2019' a una nueva columna llamada 'año'
total_creditos_2019_pachuca['año'] = 2019

# Función para formatear números con separadores de coma y dos decimales
#def format_number(x):
 #   return '{:,.2f}'.format(x)
# Formatear la columna 'montos' con la función personalizada
#total_creditos_2019_pachuca['montos'] = total_creditos_2019_pachuca['montos'].map(format_number)

total_creditos_2019_pachuca = total_creditos_2019_pachuca[['año', 'mes', 'montos']]

total_creditos_2019_pachuca

     año  mes        montos
0   2019    1  1.027393e+08
1   2019    2  9.969129e+07
2   2019    3  1.120002e+08
3   2019    4  9.428530e+07
4   2019    5  1.177026e+08
5   2019    6  1.205915e+08
6   2019    7  1.177058e+08
7   2019    8  1.379965e+08
8   2019    9  1.351398e+08
9   2019   10  1.276204e+08
10  2019   11  1.326683e+08
11  2019   12  1.779264e+08

In [7]:
total_creditos_2020_pachuca = creditos_2020_pachuca.groupby('mes')['monto'].sum().reset_index()
total_creditos_2020_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2020_pachuca['año'] = 2020
total_creditos_2020_pachuca = total_creditos_2020_pachuca[['año', 'mes', 'montos']]
total_creditos_2020_pachuca

     año  mes        montos
0   2020    1  1.237353e+08
1   2020    2  1.040559e+08
2   2020    3  1.187391e+08
3   2020    4  7.264021e+07
4   2020    5  9.400897e+07
5   2020    6  1.191117e+08
6   2020    7  1.228543e+08
7   2020    8  1.379319e+08
8   2020    9  1.776451e+08
9   2020   10  1.505281e+08
10  2020   11  1.830637e+08
11  2020   12  1.921115e+08

In [8]:
total_creditos_2021_pachuca = creditos_2021_pachuca.groupby('mes')['monto'].sum().reset_index()
total_creditos_2021_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2021_pachuca['año'] = 2021
total_creditos_2021_pachuca = total_creditos_2021_pachuca[['año', 'mes', 'montos']]
total_creditos_2021_pachuca

     año  mes        montos
0   2021    1  1.214620e+08
1   2021    2  1.552122e+08
2   2021    3  2.021506e+08
3   2021    4  1.511157e+08
4   2021    5  1.744490e+08
5   2021    6  1.626164e+08
6   2021    7  2.253961e+08
7   2021    8  1.422892e+08
8   2021    9  2.034324e+08
9   2021   10  1.377785e+08
10  2021   11  1.546064e+08
11  2021   12  2.198361e+08

In [9]:
total_creditos_2022_pachuca = creditos_2022_pachuca.groupby('mes')['monto'].sum().reset_index()
total_creditos_2022_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2022_pachuca['año'] = 2022
total_creditos_2022_pachuca = total_creditos_2022_pachuca[['año', 'mes', 'montos']]
total_creditos_2022_pachuca

     año  mes        montos
0   2022    1  1.506938e+08
1   2022    2  1.297542e+08
2   2022    3  1.931084e+08
3   2022    4  1.543661e+08
4   2022    5  1.689132e+08
5   2022    6  1.841612e+08
6   2022    7  2.049395e+08
7   2022    8  1.488898e+08
8   2022    9  2.197555e+08
9   2022   10  1.607727e+08
10  2022   11  2.062644e+08
11  2022   12  2.633340e+08

In [10]:
total_creditos_2023_pachuca = creditos_2023_pachuca.groupby('mes')['monto'].sum().reset_index()
total_creditos_2023_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2023_pachuca['año'] = 2023
total_creditos_2023_pachuca = total_creditos_2023_pachuca[['año', 'mes', 'montos']]
total_creditos_2023_pachuca

    año  mes        montos
0  2023    1  1.273210e+08
1  2023    2  1.092441e+08
2  2023    3  1.534318e+08
3  2023    4  2.308201e+07
4  2023    5  1.766667e+08
5  2023    6  1.870118e+08
6  2023    7  1.525440e+08

In [11]:
total_creditos_pachuca = pd.concat([total_creditos_2019_pachuca, total_creditos_2020_pachuca, total_creditos_2021_pachuca, total_creditos_2022_pachuca, total_creditos_2023_pachuca], ignore_index=True)
total_creditos_pachuca

     año  mes        montos
0   2019    1  1.027393e+08
1   2019    2  9.969129e+07
2   2019    3  1.120002e+08
3   2019    4  9.428530e+07
4   2019    5  1.177026e+08
5   2019    6  1.205915e+08
6   2019    7  1.177058e+08
7   2019    8  1.379965e+08
8   2019    9  1.351398e+08
9   2019   10  1.276204e+08
10  2019   11  1.326683e+08
11  2019   12  1.779264e+08
12  2020    1  1.237353e+08
13  2020    2  1.040559e+08
14  2020    3  1.187391e+08
15  2020    4  7.264021e+07
16  2020    5  9.400897e+07
17  2020    6  1.191117e+08
18  2020    7  1.228543e+08
19  2020    8  1.379319e+08
20  2020    9  1.776451e+08
21  2020   10  1.505281e+08
22  2020   11  1.830637e+08
23  2020   12  1.921115e+08
24  2021    1  1.214620e+08
25  2021    2  1.552122e+08
26  2021    3  2.021506e+08
27  2021    4  1.511157e+08
28  2021    5  1.744490e+08
29  2021    6  1.626164e+08
30  2021    7  2.253961e+08
31  2021    8  1.422892e+08
32  2021    9  2.034324e+08
33  2021   10  1.377785e+08
34  2021   11  1.546064e+08
35  2021   12  2.198361e+08
36  2022    1  1.506938e+08
37  2022    2  1.297542e+08
38  2022    3  1.931084e+08
39  2022    4  1.543661e+08
40  2022    5  1.689132e+08
41  2022    6  1.841612e+08
42  2022    7  2.049395e+08
43  2022    8  1.488898e+08
44  2022    9  2.197555e+08
45  2022   10  1.607727e+08
46  2022   11  2.062644e+08
47  2022   12  2.633340e+08
48  2023    1  1.273210e+08
49  2023    2  1.092441e+08
50  2023    3  1.534318e+08
51  2023    4  2.308201e+07
52  2023    5  1.766667e+08
53  2023    6  1.870118e+08
54  2023    7  1.525440e+08

#### *MODELO DE REGRESIÓN PARA LOS DATOS HASTA 2026*

In [12]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [13]:
# Preparar datos para el modelo
X = total_creditos_pachuca[['año', 'mes']]
y = total_creditos_pachuca['montos']
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Inicializar y entrenar el modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_train, y_train)

LinearRegression()

In [15]:
from sklearn.metrics import r2_score
# Hacer predicciones en el conjunto de prueba
y_pred = modelo.predict(X_test)
# Calcular el coeficiente de determinación (R^2)
r2 = r2_score(y_test, y_pred)
print("Coeficiente de determinación (R^2):", r2)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrático medio (MSE):", mse)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("Error absoluto medio (MAE):", mae)
rmse = np.sqrt(mse)
print("Raíz del error cuadrático medio (RMSE):", rmse)

Coeficiente de determinación (R^2): 0.1882772381902832
Error cuadrático medio (MSE): 958188726459763.5
Error absoluto medio (MAE): 24125674.20726629
Raíz del error cuadrático medio (RMSE): 30954623.66852105

##### *PREDICCIONES para los meses y años siguientes hasta diciembre de 2026*

In [16]:
# DF con todas las combinaciones posibles de año y mes para 2023 FALTANTES (AUG-DEC)
fechas_2023 = pd.DataFrame({'año': np.repeat(2023, 5),
                            'mes': range(8, 13)})

# DF con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                  'mes': np.tile(range(1, 13), 3)})
nuevas_fechas = pd.concat([fechas_2023, fechas_2024_2026]) # Concatenamos 

# Realizamos predicciones con el modelo entrenado
predicciones = modelo.predict(nuevas_fechas)
# Agregamos las predicciones al DataFrame de nuevas fechas
nuevas_fechas['montos'] = predicciones
nuevas_fechas

     año  mes        montos
0   2023    8  1.918489e+08
1   2023    9  1.991110e+08
2   2023   10  2.063731e+08
3   2023   11  2.136352e+08
4   2023   12  2.208974e+08
0   2024    1  1.546410e+08
1   2024    2  1.619031e+08
2   2024    3  1.691653e+08
3   2024    4  1.764274e+08
4   2024    5  1.836895e+08
5   2024    6  1.909516e+08
6   2024    7  1.982137e+08
7   2024    8  2.054758e+08
8   2024    9  2.127379e+08
9   2024   10  2.200000e+08
10  2024   11  2.272621e+08
11  2024   12  2.345242e+08
12  2025    1  1.682679e+08
13  2025    2  1.755300e+08
14  2025    3  1.827921e+08
15  2025    4  1.900542e+08
16  2025    5  1.973164e+08
17  2025    6  2.045785e+08
18  2025    7  2.118406e+08
19  2025    8  2.191027e+08
20  2025    9  2.263648e+08
21  2025   10  2.336269e+08
22  2025   11  2.408890e+08
23  2025   12  2.481511e+08
24  2026    1  1.818948e+08
25  2026    2  1.891569e+08
26  2026    3  1.964190e+08
27  2026    4  2.036811e+08
28  2026    5  2.109432e+08
29  2026    6  2.182053e+08
30  2026    7  2.254674e+08
31  2026    8  2.327296e+08
32  2026    9  2.399917e+08
33  2026   10  2.472538e+08
34  2026   11  2.545159e+08
35  2026   12  2.617780e+08

In [17]:
total_pachuca = pd.concat([total_creditos_pachuca, nuevas_fechas], ignore_index=True)
total_pachuca

     año  mes        montos
0   2019    1  1.027393e+08
1   2019    2  9.969129e+07
2   2019    3  1.120002e+08
3   2019    4  9.428530e+07
4   2019    5  1.177026e+08
..   ...  ...           ...
91  2026    8  2.327296e+08
92  2026    9  2.399917e+08
93  2026   10  2.472538e+08
94  2026   11  2.545159e+08
95  2026   12  2.617780e+08

[96 rows x 3 columns]

In [18]:
total_todos_pachuca = total_pachuca.groupby('año')['montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
total_todos_pachuca['modalidad'] = 'Créditos (todos)'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
# Formatear la columna 'montos' con la función personalizada
total_todos_pachuca['montos'] = total_todos_pachuca['montos'].map(format_number)

total_todos_pachuca

    año            montos         modalidad
0  2019  1,476,067,496.32  Créditos (todos)
1  2020  1,596,425,866.54  Créditos (todos)
2  2021  2,050,344,728.76  Créditos (todos)
3  2022  2,184,952,825.06  Créditos (todos)
4  2023  1,961,167,179.95  Créditos (todos)
5  2024  2,334,991,621.86  Créditos (todos)
6  2025  2,498,514,183.70  Créditos (todos)
7  2026  2,662,036,745.55  Créditos (todos)

### *Vivienda Nueva*
**Modalidad: 1**
* creditos_2019_pachuca
* creditos_2020_pachuca
* creditos_2021_pachuca
* creditos_2022_pachuca
* creditos_2023_pachuca

In [19]:
# Filtrar los datos donde 'modalidad' sea igual a '1'
creditos_2019_pachuca_modalidad_1 = creditos_2019_pachuca[creditos_2019_pachuca['modalidad'] == 1]
# Agrupar por mes y sumar los montos
total_creditos_2019_pachuca = creditos_2019_pachuca_modalidad_1.groupby('mes')['monto'].sum().reset_index()
total_creditos_2019_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2019_pachuca['año'] = 2019
total_creditos_2019_pachuca = total_creditos_2019_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2019_pachuca

     año  mes        montos
0   2019    1  7.955017e+07
1   2019    2  6.865934e+07
2   2019    3  7.813391e+07
3   2019    4  6.500411e+07
4   2019    5  7.042122e+07
5   2019    6  8.746573e+07
6   2019    7  8.074711e+07
7   2019    8  1.045717e+08
8   2019    9  9.784357e+07
9   2019   10  7.894973e+07
10  2019   11  9.374840e+07
11  2019   12  1.256562e+08

In [20]:
# Filtrar los datos donde 'modalidad' sea igual a '1'
creditos_2020_pachuca_modalidad_1 = creditos_2020_pachuca[creditos_2020_pachuca['modalidad'] == 1]
# Agrupar por mes y sumar los montos
total_creditos_2020_pachuca = creditos_2020_pachuca_modalidad_1.groupby('mes')['monto'].sum().reset_index()
total_creditos_2020_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2020_pachuca['año'] = 2020
total_creditos_2020_pachuca = total_creditos_2020_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2020_pachuca

     año  mes        montos
0   2020    1  8.963171e+07
1   2020    2  7.330905e+07
2   2020    3  8.646081e+07
3   2020    4  4.686170e+07
4   2020    5  6.383653e+07
5   2020    6  8.994808e+07
6   2020    7  8.193729e+07
7   2020    8  9.771782e+07
8   2020    9  1.195538e+08
9   2020   10  8.715167e+07
10  2020   11  9.714141e+07
11  2020   12  1.463205e+08

In [21]:
# Filtrar los datos donde 'modalidad' sea igual a '1'
creditos_2021_pachuca_modalidad_1 = creditos_2021_pachuca[creditos_2021_pachuca['modalidad'] == 1]
# Agrupar por mes y sumar los montos
total_creditos_2021_pachuca = creditos_2021_pachuca_modalidad_1.groupby('mes')['monto'].sum().reset_index()
total_creditos_2021_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2021_pachuca['año'] = 2021
total_creditos_2021_pachuca = total_creditos_2021_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2021_pachuca

     año  mes        montos
0   2021    1  8.609399e+07
1   2021    2  1.021271e+08
2   2021    3  1.310891e+08
3   2021    4  8.282697e+07
4   2021    5  1.089669e+08
5   2021    6  7.237658e+07
6   2021    7  1.311713e+08
7   2021    8  7.860909e+07
8   2021    9  1.082944e+08
9   2021   10  8.828650e+07
10  2021   11  8.905610e+07
11  2021   12  1.456424e+08

In [22]:
# Filtrar los datos donde 'modalidad' sea igual a '1'
creditos_2022_pachuca_modalidad_1 = creditos_2022_pachuca[creditos_2022_pachuca['modalidad'] == 1]
# Agrupar por mes y sumar los montos
total_creditos_2022_pachuca = creditos_2022_pachuca_modalidad_1.groupby('mes')['monto'].sum().reset_index()
total_creditos_2022_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2022_pachuca['año'] = 2022
total_creditos_2022_pachuca = total_creditos_2022_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2022_pachuca

     año  mes        montos
0   2022    1  8.764514e+07
1   2022    2  6.452677e+07
2   2022    3  8.516246e+07
3   2022    4  8.968359e+07
4   2022    5  9.198135e+07
5   2022    6  9.583941e+07
6   2022    7  1.147764e+08
7   2022    8  1.008748e+08
8   2022    9  1.191839e+08
9   2022   10  9.823773e+07
10  2022   11  1.433523e+08
11  2022   12  1.161401e+08

In [23]:
# Filtrar los datos donde 'modalidad' sea igual a '1'
creditos_2023_pachuca_modalidad_1 = creditos_2023_pachuca[creditos_2023_pachuca['modalidad'] == 1]
# Agrupar por mes y sumar los montos
total_creditos_2023_pachuca = creditos_2023_pachuca_modalidad_1.groupby('mes')['monto'].sum().reset_index()
total_creditos_2023_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2023_pachuca['año'] = 2023
total_creditos_2023_pachuca = total_creditos_2023_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2023_pachuca

    año  mes        montos
0  2023    1  8.323639e+07
1  2023    2  3.826531e+07
2  2023    3  5.808575e+07
3  2023    4  4.024524e+06
4  2023    5  1.039947e+08
5  2023    6  1.048520e+08
6  2023    7  8.783359e+07

In [24]:
total_creditos_nueva_pachuca = pd.concat([total_creditos_2019_pachuca, total_creditos_2020_pachuca, total_creditos_2021_pachuca, total_creditos_2022_pachuca, total_creditos_2023_pachuca], ignore_index=True)
total_creditos_nueva_pachuca

     año  mes        montos
0   2019    1  7.955017e+07
1   2019    2  6.865934e+07
2   2019    3  7.813391e+07
3   2019    4  6.500411e+07
4   2019    5  7.042122e+07
5   2019    6  8.746573e+07
6   2019    7  8.074711e+07
7   2019    8  1.045717e+08
8   2019    9  9.784357e+07
9   2019   10  7.894973e+07
10  2019   11  9.374840e+07
11  2019   12  1.256562e+08
12  2020    1  8.963171e+07
13  2020    2  7.330905e+07
14  2020    3  8.646081e+07
15  2020    4  4.686170e+07
16  2020    5  6.383653e+07
17  2020    6  8.994808e+07
18  2020    7  8.193729e+07
19  2020    8  9.771782e+07
20  2020    9  1.195538e+08
21  2020   10  8.715167e+07
22  2020   11  9.714141e+07
23  2020   12  1.463205e+08
24  2021    1  8.609399e+07
25  2021    2  1.021271e+08
26  2021    3  1.310891e+08
27  2021    4  8.282697e+07
28  2021    5  1.089669e+08
29  2021    6  7.237658e+07
30  2021    7  1.311713e+08
31  2021    8  7.860909e+07
32  2021    9  1.082944e+08
33  2021   10  8.828650e+07
34  2021   11  8.905610e+07
35  2021   12  1.456424e+08
36  2022    1  8.764514e+07
37  2022    2  6.452677e+07
38  2022    3  8.516246e+07
39  2022    4  8.968359e+07
40  2022    5  9.198135e+07
41  2022    6  9.583941e+07
42  2022    7  1.147764e+08
43  2022    8  1.008748e+08
44  2022    9  1.191839e+08
45  2022   10  9.823773e+07
46  2022   11  1.433523e+08
47  2022   12  1.161401e+08
48  2023    1  8.323639e+07
49  2023    2  3.826531e+07
50  2023    3  5.808575e+07
51  2023    4  4.024524e+06
52  2023    5  1.039947e+08
53  2023    6  1.048520e+08
54  2023    7  8.783359e+07

#### *MODELO DE REGRESIÓN PARA LOS DATOS HASTA 2026*

In [25]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [26]:
# Preparar datos para el modelo
X = total_creditos_nueva_pachuca[['año', 'mes']]
y = total_creditos_nueva_pachuca['montos']
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
# Inicializar y entrenar el modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_train, y_train)

LinearRegression()

In [28]:
from sklearn.metrics import r2_score
# Hacer predicciones en el conjunto de prueba
y_pred = modelo.predict(X_test)
# Calcular el coeficiente de determinación (R^2)
r2 = r2_score(y_test, y_pred)
print("Coeficiente de determinación (R^2):", r2)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrático medio (MSE):", mse)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("Error absoluto medio (MAE):", mae)
rmse = np.sqrt(mse)
print("Raíz del error cuadrático medio (RMSE):", rmse)

Coeficiente de determinación (R^2): -0.01703058558648607
Error cuadrático medio (MSE): 508649519469343.44
Error absoluto medio (MAE): 14959219.968036445
Raíz del error cuadrático medio (RMSE): 22553259.619605843

##### *PREDICCIONES para los meses y años siguientes hasta diciembre de 2026*

In [29]:
# DF con todas las combinaciones posibles de año y mes para 2023 FALTANTES (AUG-DEC)
fechas_2023 = pd.DataFrame({'año': np.repeat(2023, 5),
                            'mes': range(8, 13)})

# DF con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                  'mes': np.tile(range(1, 13), 3)})
nuevas_fechas_nueva = pd.concat([fechas_2023, fechas_2024_2026]) # Concatenamos 

# Realizamos predicciones con el modelo entrenado
predicciones = modelo.predict(nuevas_fechas_nueva)
# Agregamos las predicciones al DataFrame de nuevas fechas
nuevas_fechas_nueva['montos'] = predicciones
nuevas_fechas_nueva

     año  mes        montos
0   2023    8  1.021814e+08
1   2023    9  1.065898e+08
2   2023   10  1.109982e+08
3   2023   11  1.154066e+08
4   2023   12  1.198150e+08
0   2024    1  7.303618e+07
1   2024    2  7.744456e+07
2   2024    3  8.185295e+07
3   2024    4  8.626133e+07
4   2024    5  9.066971e+07
5   2024    6  9.507809e+07
6   2024    7  9.948648e+07
7   2024    8  1.038949e+08
8   2024    9  1.083032e+08
9   2024   10  1.127116e+08
10  2024   11  1.171200e+08
11  2024   12  1.215284e+08
12  2025    1  7.474961e+07
13  2025    2  7.915799e+07
14  2025    3  8.356637e+07
15  2025    4  8.797475e+07
16  2025    5  9.238314e+07
17  2025    6  9.679152e+07
18  2025    7  1.011999e+08
19  2025    8  1.056083e+08
20  2025    9  1.100167e+08
21  2025   10  1.144250e+08
22  2025   11  1.188334e+08
23  2025   12  1.232418e+08
24  2026    1  7.646303e+07
25  2026    2  8.087142e+07
26  2026    3  8.527980e+07
27  2026    4  8.968818e+07
28  2026    5  9.409656e+07
29  2026    6  9.850494e+07
30  2026    7  1.029133e+08
31  2026    8  1.073217e+08
32  2026    9  1.117301e+08
33  2026   10  1.161385e+08
34  2026   11  1.205469e+08
35  2026   12  1.249552e+08

#Creamos un DataFrame con todas las combinaciones posibles de año y mes
nuevas_fechas_nueva = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                              'mes': np.tile(range(1, 13), 3)})
#Realizamos predicciones con el modelo entrenado
predicciones = modelo.predict(nuevas_fechas_nueva)
#Agregamos las predicciones al DataFrame de nuevas fechas
nuevas_fechas_nueva['montos'] = predicciones
nuevas_fechas_nueva

In [30]:
total_nueva_pachuca = pd.concat([total_creditos_nueva_pachuca, nuevas_fechas_nueva], ignore_index=True)
total_nueva_pachuca

     año  mes        montos
0   2019    1  7.955017e+07
1   2019    2  6.865934e+07
2   2019    3  7.813391e+07
3   2019    4  6.500411e+07
4   2019    5  7.042122e+07
..   ...  ...           ...
91  2026    8  1.073217e+08
92  2026    9  1.117301e+08
93  2026   10  1.161385e+08
94  2026   11  1.205469e+08
95  2026   12  1.249552e+08

[96 rows x 3 columns]

In [31]:
total_nueva_pachuca = total_nueva_pachuca.groupby('año')['montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
total_nueva_pachuca['modalidad'] = 'Nueva'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
total_nueva_pachuca['montos'] = total_nueva_pachuca['montos'].map(format_number)

total_nueva_pachuca

    año            montos modalidad
0  2019  1,030,751,267.28     Nueva
1  2020  1,079,870,382.75     Nueva
2  2021  1,224,540,479.98     Nueva
3  2022  1,207,403,961.25     Nueva
4  2023  1,035,283,198.58     Nueva
5  2024  1,167,387,411.17     Nueva
6  2025  1,187,948,514.65     Nueva
7  2026  1,208,509,618.13     Nueva

### *Vivienda Usada*
**Modalidad: 3**

In [32]:
# Filtrar los datos donde 'modalidad' sea igual a '3'
creditos_2019_pachuca_modalidad_3 = creditos_2019_pachuca[creditos_2019_pachuca['modalidad'] == 3]
# Agrupar por mes y sumar los montos
total_creditos_2019_pachuca = creditos_2019_pachuca_modalidad_3.groupby('mes')['monto'].sum().reset_index()
total_creditos_2019_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2019_pachuca['año'] = 2019
total_creditos_2019_pachuca = total_creditos_2019_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2019_pachuca

     año  mes       montos
0   2019    1  18394326.86
1   2019    2  28519033.44
2   2019    3  27727681.21
3   2019    4  27303028.49
4   2019    5  38099339.14
5   2019    6  30389506.23
6   2019    7  29593997.21
7   2019    8  31746217.05
8   2019    9  31157273.37
9   2019   10  40195442.10
10  2019   11  28943113.96
11  2019   12  47196147.53

In [33]:
# Filtrar los datos donde 'modalidad' sea igual a '3'
creditos_2020_pachuca_modalidad_3 = creditos_2020_pachuca[creditos_2020_pachuca['modalidad'] == 3]
# Agrupar por mes y sumar los montos
total_creditos_2020_pachuca = creditos_2020_pachuca_modalidad_3.groupby('mes')['monto'].sum().reset_index()
total_creditos_2020_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2020_pachuca['año'] = 2020
total_creditos_2020_pachuca = total_creditos_2020_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2020_pachuca

     año  mes       montos
0   2020    1  30383812.26
1   2020    2  25831656.80
2   2020    3  22463181.96
3   2020    4  11915884.89
4   2020    5  22469908.20
5   2020    6  23197212.34
6   2020    7  30376591.72
7   2020    8  38619869.89
8   2020    9  40972408.35
9   2020   10  58167267.31
10  2020   11  71803834.81
11  2020   12  41066719.01

In [34]:
creditos_2021_pachuca_modalidad_3 = creditos_2021_pachuca[creditos_2021_pachuca['modalidad'] == 3]
# Agrupar por mes y sumar los montos
total_creditos_2021_pachuca = creditos_2021_pachuca_modalidad_3.groupby('mes')['monto'].sum().reset_index()
total_creditos_2021_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2021_pachuca['año'] = 2021
total_creditos_2021_pachuca = total_creditos_2021_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2021_pachuca

     año  mes       montos
0   2021    1  28665893.45
1   2021    2  34402318.34
2   2021    3  55745884.69
3   2021    4  58956960.73
4   2021    5  45911602.09
5   2021    6  77986542.39
6   2021    7  80678813.56
7   2021    8  43693388.21
8   2021    9  53846417.51
9   2021   10  32537705.73
10  2021   11  52398724.22
11  2021   12  63383918.82

In [35]:
creditos_2022_pachuca_modalidad_3 = creditos_2022_pachuca[creditos_2022_pachuca['modalidad'] == 3]
# Agrupar por mes y sumar los montos
total_creditos_2022_pachuca = creditos_2022_pachuca_modalidad_3.groupby('mes')['monto'].sum().reset_index()
total_creditos_2022_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2022_pachuca['año'] = 2022
total_creditos_2022_pachuca = total_creditos_2022_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2022_pachuca

     año  mes        montos
0   2022    1  5.160283e+07
1   2022    2  4.412415e+07
2   2022    3  8.809292e+07
3   2022    4  5.859451e+07
4   2022    5  6.845188e+07
5   2022    6  5.896624e+07
6   2022    7  8.418067e+07
7   2022    8  3.885549e+07
8   2022    9  9.549629e+07
9   2022   10  5.526082e+07
10  2022   11  5.866558e+07
11  2022   12  1.361032e+08

In [36]:
creditos_2023_pachuca_modalidad_3 = creditos_2023_pachuca[creditos_2023_pachuca['modalidad'] == 3]
# Agrupar por mes y sumar los montos
total_creditos_2023_pachuca = creditos_2023_pachuca_modalidad_3.groupby('mes')['monto'].sum().reset_index()
total_creditos_2023_pachuca.rename(columns={'monto': 'montos'}, inplace=True)
total_creditos_2023_pachuca['año'] = 2023
total_creditos_2023_pachuca = total_creditos_2023_pachuca[['año', 'mes', 'montos']] # Reordenar las columnas

total_creditos_2023_pachuca

    año  mes       montos
0  2023    1  36352545.99
1  2023    2  63804077.43
2  2023    3  72046418.37
3  2023    4  19030483.44
4  2023    5  58391091.29
5  2023    6  69232646.30
6  2023    7  55893725.77

In [37]:
total_creditos_usada_pachuca = pd.concat([total_creditos_2019_pachuca, total_creditos_2020_pachuca, total_creditos_2021_pachuca, total_creditos_2022_pachuca, total_creditos_2023_pachuca], ignore_index=True)
total_creditos_usada_pachuca

     año  mes        montos
0   2019    1  1.839433e+07
1   2019    2  2.851903e+07
2   2019    3  2.772768e+07
3   2019    4  2.730303e+07
4   2019    5  3.809934e+07
5   2019    6  3.038951e+07
6   2019    7  2.959400e+07
7   2019    8  3.174622e+07
8   2019    9  3.115727e+07
9   2019   10  4.019544e+07
10  2019   11  2.894311e+07
11  2019   12  4.719615e+07
12  2020    1  3.038381e+07
13  2020    2  2.583166e+07
14  2020    3  2.246318e+07
15  2020    4  1.191588e+07
16  2020    5  2.246991e+07
17  2020    6  2.319721e+07
18  2020    7  3.037659e+07
19  2020    8  3.861987e+07
20  2020    9  4.097241e+07
21  2020   10  5.816727e+07
22  2020   11  7.180383e+07
23  2020   12  4.106672e+07
24  2021    1  2.866589e+07
25  2021    2  3.440232e+07
26  2021    3  5.574588e+07
27  2021    4  5.895696e+07
28  2021    5  4.591160e+07
29  2021    6  7.798654e+07
30  2021    7  8.067881e+07
31  2021    8  4.369339e+07
32  2021    9  5.384642e+07
33  2021   10  3.253771e+07
34  2021   11  5.239872e+07
35  2021   12  6.338392e+07
36  2022    1  5.160283e+07
37  2022    2  4.412415e+07
38  2022    3  8.809292e+07
39  2022    4  5.859451e+07
40  2022    5  6.845188e+07
41  2022    6  5.896624e+07
42  2022    7  8.418067e+07
43  2022    8  3.885549e+07
44  2022    9  9.549629e+07
45  2022   10  5.526082e+07
46  2022   11  5.866558e+07
47  2022   12  1.361032e+08
48  2023    1  3.635255e+07
49  2023    2  6.380408e+07
50  2023    3  7.204642e+07
51  2023    4  1.903048e+07
52  2023    5  5.839109e+07
53  2023    6  6.923265e+07
54  2023    7  5.589373e+07

#### *MODELO DE REGRESIÓN PARA LOS DATOS HASTA 2026*

In [38]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [39]:
# Preparar datos para el modelo
X = total_creditos_usada_pachuca[['año', 'mes']]
y = total_creditos_usada_pachuca['montos']
# Dividir los datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [40]:
# Inicializar y entrenar el modelo de regresión lineal
modelo = LinearRegression()
modelo.fit(X_train, y_train)

LinearRegression()

In [41]:
from sklearn.metrics import r2_score
# Hacer predicciones en el conjunto de prueba
y_pred = modelo.predict(X_test)
# Calcular el coeficiente de determinación (R^2)
r2 = r2_score(y_test, y_pred)
print("Coeficiente de determinación (R^2):", r2)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print("Error cuadrático medio (MSE):", mse)

from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_test, y_pred)
print("Error absoluto medio (MAE):", mae)
rmse = np.sqrt(mse)
print("Raíz del error cuadrático medio (RMSE):", rmse)

Coeficiente de determinación (R^2): 0.23282011825675786
Error cuadrático medio (MSE): 125208338348372.6
Error absoluto medio (MAE): 8364801.243545852
Raíz del error cuadrático medio (RMSE): 11189653.182667129

##### *PREDICCIONES para los meses y años siguientes hasta diciembre de 2026*

In [42]:
# DF con todas las combinaciones posibles de año y mes para 2023 FALTANTES (AUG-DEC)
fechas_2023 = pd.DataFrame({'año': np.repeat(2023, 5),
                            'mes': range(8, 13)})

# DF con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                  'mes': np.tile(range(1, 13), 3)})
nuevas_fechas_usada = pd.concat([fechas_2023, fechas_2024_2026]) # Concatenamos 

# Realizamos predicciones con el modelo entrenado
predicciones = modelo.predict(nuevas_fechas_usada)
# Agregamos las predicciones al DataFrame de nuevas fechas
nuevas_fechas_usada['montos'] = predicciones
nuevas_fechas_usada

     año  mes        montos
0   2023    8  7.751189e+07
1   2023    9  8.047184e+07
2   2023   10  8.343178e+07
3   2023   11  8.639173e+07
4   2023   12  8.935167e+07
0   2024    1  6.753942e+07
1   2024    2  7.049936e+07
2   2024    3  7.345931e+07
3   2024    4  7.641925e+07
4   2024    5  7.937920e+07
5   2024    6  8.233914e+07
6   2024    7  8.529909e+07
7   2024    8  8.825903e+07
8   2024    9  9.121898e+07
9   2024   10  9.417893e+07
10  2024   11  9.713887e+07
11  2024   12  1.000988e+08
12  2025    1  7.828656e+07
13  2025    2  8.124650e+07
14  2025    3  8.420645e+07
15  2025    4  8.716640e+07
16  2025    5  9.012634e+07
17  2025    6  9.308629e+07
18  2025    7  9.604623e+07
19  2025    8  9.900618e+07
20  2025    9  1.019661e+08
21  2025   10  1.049261e+08
22  2025   11  1.078860e+08
23  2025   12  1.108460e+08
24  2026    1  8.903370e+07
25  2026    2  9.199365e+07
26  2026    3  9.495359e+07
27  2026    4  9.791354e+07
28  2026    5  1.008735e+08
29  2026    6  1.038334e+08
30  2026    7  1.067934e+08
31  2026    8  1.097533e+08
32  2026    9  1.127133e+08
33  2026   10  1.156732e+08
34  2026   11  1.186332e+08
35  2026   12  1.215931e+08

#Creamos un DataFrame con todas las combinaciones posibles de año y mes
nuevas_fechas_usada = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                              'mes': np.tile(range(1, 13), 3)})
#Realizamos predicciones con el modelo entrenado
predicciones = modelo.predict(nuevas_fechas_usada)
#Agregamos las predicciones al DataFrame de nuevas fechas
nuevas_fechas_usada['montos'] = predicciones
nuevas_fechas_usada

In [43]:
total_usada_pachuca = pd.concat([total_creditos_usada_pachuca, nuevas_fechas_usada], ignore_index=True)
total_usada_pachuca

     año  mes        montos
0   2019    1  1.839433e+07
1   2019    2  2.851903e+07
2   2019    3  2.772768e+07
3   2019    4  2.730303e+07
4   2019    5  3.809934e+07
..   ...  ...           ...
91  2026    8  1.097533e+08
92  2026    9  1.127133e+08
93  2026   10  1.156732e+08
94  2026   11  1.186332e+08
95  2026   12  1.215931e+08

[96 rows x 3 columns]

In [44]:
total_usada_pachuca = total_usada_pachuca.groupby('año')['montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
total_usada_pachuca['modalidad'] = 'Usada'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
total_usada_pachuca['montos'] = total_usada_pachuca['montos'].map(format_number)
total_usada_pachuca

    año            montos modalidad
0  2019    379,265,106.59     Usada
1  2020    417,268,347.54     Usada
2  2021    628,208,169.74     Usada
3  2022    838,394,556.75     Usada
4  2023    791,909,895.45     Usada
5  2024  1,005,829,390.08     Usada
6  2025  1,134,795,117.70     Usada
7  2026  1,263,760,845.32     Usada

___
# *Gráfica totales*

In [45]:
forecast_creditosgral_totales_pachuca = pd.concat([total_todos_pachuca, total_nueva_pachuca,total_usada_pachuca], ignore_index=True)
forecast_creditosgral_totales_pachuca

     año            montos         modalidad
0   2019  1,476,067,496.32  Créditos (todos)
1   2020  1,596,425,866.54  Créditos (todos)
2   2021  2,050,344,728.76  Créditos (todos)
3   2022  2,184,952,825.06  Créditos (todos)
4   2023  1,961,167,179.95  Créditos (todos)
5   2024  2,334,991,621.86  Créditos (todos)
6   2025  2,498,514,183.70  Créditos (todos)
7   2026  2,662,036,745.55  Créditos (todos)
8   2019  1,030,751,267.28             Nueva
9   2020  1,079,870,382.75             Nueva
10  2021  1,224,540,479.98             Nueva
11  2022  1,207,403,961.25             Nueva
12  2023  1,035,283,198.58             Nueva
13  2024  1,167,387,411.17             Nueva
14  2025  1,187,948,514.65             Nueva
15  2026  1,208,509,618.13             Nueva
16  2019    379,265,106.59             Usada
17  2020    417,268,347.54             Usada
18  2021    628,208,169.74             Usada
19  2022    838,394,556.75             Usada
20  2023    791,909,895.45             Usada
21  2024  1,005,829,390.08             Usada
22  2025  1,134,795,117.70             Usada
23  2026  1,263,760,845.32             Usada

In [46]:
# Datos
trimestres = forecast_creditosgral_totales_pachuca['año']
modalidades = forecast_creditosgral_totales_pachuca['modalidad']
montos = forecast_creditosgral_totales_pachuca['montos']

# Limpiar las cadenas de montos y convertirlas a números
promedios_limpios = [float(montos.replace(',', '')) for montos in montos]

fig = go.Figure()
# Agregar líneas para cada modalidad
for modalidad in modalidades.unique():
    df_modalidad = forecast_creditosgral_totales_pachuca[forecast_creditosgral_totales_pachuca['modalidad'] == modalidad]
    fig.add_trace(go.Scatter(
        x=df_modalidad['año'],
        y=df_modalidad['montos'].apply(lambda x: float(x.replace(',', ''))),  # Usar los montos limpios
        mode='markers+lines',
        name=modalidad
    ))

fig.update_layout(
    title='Monto total anual',
    yaxis=dict(gridcolor='#dddcda'),
    plot_bgcolor='rgba(0,0,0,0)',  # Color de fondo del gráfico
)

# Agregar etiquetas de texto a los puntos
for trace in fig.data:
    df_modalidad = forecast_creditosgral_totales_pachuca[forecast_creditosgral_totales_pachuca['modalidad'] == trace.name]
    for i, point in enumerate(trace.y):
        fig.add_annotation(
            x=trace.x[i], 
            y=point, 
            text=f'{df_modalidad.iloc[i]["montos"]}', 
            showarrow=False,
            font=dict(color='black', size=10),
            yshift=10
        )

# Exportar gráfica como archivo HTML
def guardar_grafico_como_html(fig, nombre_archivo, carpeta='graficas'):
    # Crear la carpeta si no existe
    if not os.path.exists(carpeta):
        os.makedirs(carpeta)
    
    # Gráfica como archivo HTML en la carpeta especificada
    pio.write_html(fig, f'{carpeta}/{nombre_archivo}.html')

guardar_grafico_como_html(fig, 'g_scatt_forecastcreditgral_total_pachuca', carpeta='graficas')
fig.show()

___
___
# **Promedio Forecast créditos generales (valor)**

In [47]:
# Para el año 2019
promedio_creditos_2019_pachuca = creditos_2019_pachuca.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
promedio_creditos_2019_pachuca.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
promedio_creditos_2019_pachuca['promedio_montos'] = promedio_creditos_2019_pachuca['montos'] / promedio_creditos_2019_pachuca['num_creditos']
promedio_creditos_2019_pachuca['año'] = 2019
promedio_creditos_2019_pachuca = promedio_creditos_2019_pachuca[['año', 'mes', 'montos', 'promedio_montos']]
promedio_creditos_2019_pachuca

     año  mes        montos  promedio_montos
0   2019    1  1.027393e+08     1.317171e+06
1   2019    2  9.969129e+07     1.145877e+06
2   2019    3  1.120002e+08     1.272730e+06
3   2019    4  9.428530e+07     1.193485e+06
4   2019    5  1.177026e+08     1.142744e+06
5   2019    6  1.205915e+08     1.182270e+06
6   2019    7  1.177058e+08     1.121008e+06
7   2019    8  1.379965e+08     1.314252e+06
8   2019    9  1.351398e+08     1.312037e+06
9   2019   10  1.276204e+08     1.192714e+06
10  2019   11  1.326683e+08     1.143692e+06
11  2019   12  1.779264e+08     1.253003e+06

In [48]:
# Para el año 2020
promedio_creditos_2020_pachuca = creditos_2020_pachuca.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
promedio_creditos_2020_pachuca.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
promedio_creditos_2020_pachuca['promedio_montos'] = promedio_creditos_2020_pachuca['montos'] / promedio_creditos_2020_pachuca['num_creditos']
promedio_creditos_2020_pachuca['año'] = 2020
promedio_creditos_2020_pachuca = promedio_creditos_2020_pachuca[['año', 'mes', 'montos', 'promedio_montos']]
promedio_creditos_2020_pachuca

     año  mes        montos  promedio_montos
0   2020    1  1.237353e+08     1.406083e+06
1   2020    2  1.040559e+08     1.238761e+06
2   2020    3  1.187391e+08     1.187391e+06
3   2020    4  7.264021e+07     1.482453e+06
4   2020    5  9.400897e+07     1.119154e+06
5   2020    6  1.191117e+08     1.280771e+06
6   2020    7  1.228543e+08     1.170041e+06
7   2020    8  1.379319e+08     1.499259e+06
8   2020    9  1.776451e+08     1.315889e+06
9   2020   10  1.505281e+08     1.447386e+06
10  2020   11  1.830637e+08     1.634497e+06
11  2020   12  1.921115e+08     1.455390e+06

In [49]:
# Para el año 2021
promedio_creditos_2021_pachuca = creditos_2021_pachuca.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
promedio_creditos_2021_pachuca.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
promedio_creditos_2021_pachuca['promedio_montos'] = promedio_creditos_2021_pachuca['montos'] / promedio_creditos_2021_pachuca['num_creditos']
promedio_creditos_2021_pachuca['año'] = 2021
promedio_creditos_2021_pachuca = promedio_creditos_2021_pachuca[['año', 'mes', 'montos', 'promedio_montos']]
promedio_creditos_2021_pachuca

     año  mes        montos  promedio_montos
0   2021    1  1.214620e+08     1.499531e+06
1   2021    2  1.552122e+08     1.385823e+06
2   2021    3  2.021506e+08     1.486401e+06
3   2021    4  1.511157e+08     1.208926e+06
4   2021    5  1.744490e+08     1.516948e+06
5   2021    6  1.626164e+08     1.250895e+06
6   2021    7  2.253961e+08     1.587296e+06
7   2021    8  1.422892e+08     1.237298e+06
8   2021    9  2.034324e+08     1.640584e+06
9   2021   10  1.377785e+08     1.337655e+06
10  2021   11  1.546064e+08     1.405513e+06
11  2021   12  2.198361e+08     1.604643e+06

In [50]:
# Para el año 2022
promedio_creditos_2022_pachuca = creditos_2022_pachuca.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
promedio_creditos_2022_pachuca.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
promedio_creditos_2022_pachuca['promedio_montos'] = promedio_creditos_2022_pachuca['montos'] / promedio_creditos_2022_pachuca['num_creditos']
promedio_creditos_2022_pachuca['año'] = 2022
promedio_creditos_2022_pachuca = promedio_creditos_2022_pachuca[['año', 'mes', 'montos', 'promedio_montos']]
promedio_creditos_2022_pachuca

     año  mes        montos  promedio_montos
0   2022    1  1.506938e+08     1.477390e+06
1   2022    2  1.297542e+08     1.365834e+06
2   2022    3  1.931084e+08     1.462942e+06
3   2022    4  1.543661e+08     1.354089e+06
4   2022    5  1.689132e+08     1.741373e+06
5   2022    6  1.841612e+08     1.644296e+06
6   2022    7  2.049395e+08     1.652738e+06
7   2022    8  1.488898e+08     1.567261e+06
8   2022    9  2.197555e+08     1.801274e+06
9   2022   10  1.607727e+08     1.435471e+06
10  2022   11  2.062644e+08     1.676946e+06
11  2022   12  2.633340e+08     1.645837e+06

In [51]:
# Para el año 2023
promedio_creditos_2023_pachuca = creditos_2023_pachuca.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
promedio_creditos_2023_pachuca.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
promedio_creditos_2023_pachuca['promedio_montos'] = promedio_creditos_2023_pachuca['montos'] / promedio_creditos_2023_pachuca['num_creditos']
promedio_creditos_2023_pachuca['año'] = 2023
promedio_creditos_2023_pachuca = promedio_creditos_2023_pachuca[['año', 'mes', 'montos', 'promedio_montos']]
promedio_creditos_2023_pachuca

    año  mes        montos  promedio_montos
0  2023    1  1.273210e+08     1.446830e+06
1  2023    2  1.092441e+08     1.316195e+06
2  2023    3  1.534318e+08     1.581771e+06
3  2023    4  2.308201e+07     1.154100e+06
4  2023    5  1.766667e+08     1.218391e+06
5  2023    6  1.870118e+08     1.289736e+06
6  2023    7  1.525440e+08     1.481010e+06

In [52]:
promedio_creditos_pachuca = pd.concat([
promedio_creditos_2019_pachuca,
promedio_creditos_2020_pachuca,
promedio_creditos_2021_pachuca,
promedio_creditos_2022_pachuca,
promedio_creditos_2023_pachuca,
], ignore_index=True)
promedio_creditos_pachuca

     año  mes        montos  promedio_montos
0   2019    1  1.027393e+08     1.317171e+06
1   2019    2  9.969129e+07     1.145877e+06
2   2019    3  1.120002e+08     1.272730e+06
3   2019    4  9.428530e+07     1.193485e+06
4   2019    5  1.177026e+08     1.142744e+06
5   2019    6  1.205915e+08     1.182270e+06
6   2019    7  1.177058e+08     1.121008e+06
7   2019    8  1.379965e+08     1.314252e+06
8   2019    9  1.351398e+08     1.312037e+06
9   2019   10  1.276204e+08     1.192714e+06
10  2019   11  1.326683e+08     1.143692e+06
11  2019   12  1.779264e+08     1.253003e+06
12  2020    1  1.237353e+08     1.406083e+06
13  2020    2  1.040559e+08     1.238761e+06
14  2020    3  1.187391e+08     1.187391e+06
15  2020    4  7.264021e+07     1.482453e+06
16  2020    5  9.400897e+07     1.119154e+06
17  2020    6  1.191117e+08     1.280771e+06
18  2020    7  1.228543e+08     1.170041e+06
19  2020    8  1.379319e+08     1.499259e+06
20  2020    9  1.776451e+08     1.315889e+06
21  2020   10  1.505281e+08     1.447386e+06
22  2020   11  1.830637e+08     1.634497e+06
23  2020   12  1.921115e+08     1.455390e+06
24  2021    1  1.214620e+08     1.499531e+06
25  2021    2  1.552122e+08     1.385823e+06
26  2021    3  2.021506e+08     1.486401e+06
27  2021    4  1.511157e+08     1.208926e+06
28  2021    5  1.744490e+08     1.516948e+06
29  2021    6  1.626164e+08     1.250895e+06
30  2021    7  2.253961e+08     1.587296e+06
31  2021    8  1.422892e+08     1.237298e+06
32  2021    9  2.034324e+08     1.640584e+06
33  2021   10  1.377785e+08     1.337655e+06
34  2021   11  1.546064e+08     1.405513e+06
35  2021   12  2.198361e+08     1.604643e+06
36  2022    1  1.506938e+08     1.477390e+06
37  2022    2  1.297542e+08     1.365834e+06
38  2022    3  1.931084e+08     1.462942e+06
39  2022    4  1.543661e+08     1.354089e+06
40  2022    5  1.689132e+08     1.741373e+06
41  2022    6  1.841612e+08     1.644296e+06
42  2022    7  2.049395e+08     1.652738e+06
43  2022    8  1.488898e+08     1.567261e+06
44  2022    9  2.197555e+08     1.801274e+06
45  2022   10  1.607727e+08     1.435471e+06
46  2022   11  2.062644e+08     1.676946e+06
47  2022   12  2.633340e+08     1.645837e+06
48  2023    1  1.273210e+08     1.446830e+06
49  2023    2  1.092441e+08     1.316195e+06
50  2023    3  1.534318e+08     1.581771e+06
51  2023    4  2.308201e+07     1.154100e+06
52  2023    5  1.766667e+08     1.218391e+06
53  2023    6  1.870118e+08     1.289736e+06
54  2023    7  1.525440e+08     1.481010e+06

### *PROMEDIOS*
#### *MODELO DE REGRESIÓN PARA LOS DATOS HASTA 2026*

MONTOS

In [53]:
X_montos = promedio_creditos_pachuca[['año', 'mes']]
y_montos = promedio_creditos_pachuca['montos']
# Datos en conjuntos de entrenamiento y prueba
X_train_montos, X_test_montos, y_train_montos, y_test_montos = train_test_split(X_montos, y_montos, test_size=0.2, random_state=42)
# Modelo de montos
modelo_montos = LinearRegression()
modelo_montos.fit(X_train_montos, y_train_montos)

LinearRegression()

In [54]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Hacer predicciones en el conjunto de prueba para el modelo de montos
y_pred_montos = modelo_montos.predict(X_test_montos)
# Calcular el coeficiente de determinación (R^2) para el modelo de montos
r2_montos = r2_score(y_test_montos, y_pred_montos)
print("Coeficiente de determinación (R^2) para el modelo de montos:", r2_montos)
# Calcular el error cuadrático medio (MSE) para el modelo de montos
mse_montos = mean_squared_error(y_test_montos, y_pred_montos)
print("Error cuadrático medio (MSE) para el modelo de montos:", mse_montos)
# Calcular el error absoluto medio (MAE) para el modelo de montos
mae_montos = mean_absolute_error(y_test_montos, y_pred_montos)
print("Error absoluto medio (MAE) para el modelo de montos:", mae_montos)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de montos
rmse_montos = np.sqrt(mse_montos)
print("Raíz del error cuadrático medio (RMSE) para el modelo de montos:", rmse_montos)

Coeficiente de determinación (R^2) para el modelo de montos: 0.1882772381902832
Error cuadrático medio (MSE) para el modelo de montos: 958188726459763.5
Error absoluto medio (MAE) para el modelo de montos: 24125674.20726629
Raíz del error cuadrático medio (RMSE) para el modelo de montos: 30954623.66852105

PROMEDIO

In [55]:
# Preparar datos para el modelo de promedio
X_promedio = promedio_creditos_pachuca[['año', 'mes']]
y_promedio = promedio_creditos_pachuca['promedio_montos']
# Dividir los datos de promedio en conjuntos de entrenamiento y prueba
X_train_promedio, X_test_promedio, y_train_promedio, y_test_promedio = train_test_split(X_promedio, y_promedio, test_size=0.2, random_state=42)
# Entrenar modelo de promedio
modelo_promedio = LinearRegression()
modelo_promedio.fit(X_train_promedio, y_train_promedio)

LinearRegression()

In [56]:
# Predicciones en el conjunto de prueba para el modelo de promedio
y_pred_promedio = modelo_promedio.predict(X_test_promedio)
# Calcular el coeficiente de determinación (R^2) para el modelo de promedio
r2_promedio = r2_score(y_test_promedio, y_pred_promedio)
print("Coeficiente de determinación (R^2) para el modelo de promedio:", r2_promedio)
# Calcular el error cuadrático medio (MSE) para el modelo de promedio
mse_promedio = mean_squared_error(y_test_promedio, y_pred_promedio)
print("Error cuadrático medio (MSE) para el modelo de promedio:", mse_promedio)
# Calcular el error absoluto medio (MAE) para el modelo de promedio
mae_promedio = mean_absolute_error(y_test_promedio, y_pred_promedio)
print("Error absoluto medio (MAE) para el modelo de promedio:", mae_promedio)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de promedio
rmse_promedio = np.sqrt(mse_promedio)
print("Raíz del error cuadrático medio (RMSE) para el modelo de promedio:", rmse_promedio)

Coeficiente de determinación (R^2) para el modelo de promedio: -0.0378335032178343
Error cuadrático medio (MSE) para el modelo de promedio: 28554654281.235367
Error absoluto medio (MAE) para el modelo de promedio: 149207.84976951443
Raíz del error cuadrático medio (RMSE) para el modelo de promedio: 168981.22464118717

In [57]:
# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2023 (agosto a diciembre)
fechas_2023_faltantes = pd.DataFrame({'año': np.repeat(2023, 5),
                                      'mes': range(8, 13)})

# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024 = pd.DataFrame({'año': np.repeat(2024, 12),
                             'mes': range(1, 13)})
fechas_2025 = pd.DataFrame({'año': np.repeat(2025, 12),
                             'mes': range(1, 13)})
fechas_2026 = pd.DataFrame({'año': np.repeat(2026, 12),
                             'mes': range(1, 13)})

# Concatenar los DataFrames para obtener el DataFrame completo de 2024-2026
fechas_2023_2026 = pd.concat([fechas_2023_faltantes, fechas_2024, fechas_2025, fechas_2026])

# Realizar predicciones con el modelo de montos para 2023 (agosto a diciembre)
predicciones_montos_2023 = modelo_montos.predict(fechas_2023_faltantes[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2023 (agosto a diciembre)
predicciones_promedio_2023 = modelo_promedio.predict(fechas_2023_faltantes[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2023 (agosto a diciembre)
fechas_2023_faltantes['montos_predichos'] = predicciones_montos_2023
fechas_2023_faltantes['promedio_montos_predicho'] = predicciones_promedio_2023

# Realizar predicciones con el modelo de montos para 2024-2026
predicciones_montos_2024_2026 = modelo_montos.predict(fechas_2023_2026[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2024-2026
predicciones_promedio_2024_2026 = modelo_promedio.predict(fechas_2023_2026[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2024-2026
fechas_2023_2026['montos_predichos'] = predicciones_montos_2024_2026
fechas_2023_2026['promedio_montos_predicho'] = predicciones_promedio_2024_2026

# Concatenar los DataFrames para obtener el resultado final
nuevas_fechas = pd.concat([fechas_2023_faltantes, fechas_2023_2026])

nuevas_fechas

     año  mes  montos_predichos  promedio_montos_predicho
0   2023    8      1.918489e+08              1.585940e+06
1   2023    9      1.991110e+08              1.601280e+06
2   2023   10      2.063731e+08              1.616620e+06
3   2023   11      2.136352e+08              1.631960e+06
4   2023   12      2.208974e+08              1.647300e+06
0   2023    8      1.918489e+08              1.585940e+06
1   2023    9      1.991110e+08              1.601280e+06
2   2023   10      2.063731e+08              1.616620e+06
3   2023   11      2.136352e+08              1.631960e+06
4   2023   12      2.208974e+08              1.647300e+06
0   2024    1      1.546410e+08              1.557764e+06
1   2024    2      1.619031e+08              1.573104e+06
2   2024    3      1.691653e+08              1.588444e+06
3   2024    4      1.764274e+08              1.603784e+06
4   2024    5      1.836895e+08              1.619124e+06
5   2024    6      1.909516e+08              1.634464e+06
6   2024    7      1.982137e+08              1.649804e+06
7   2024    8      2.054758e+08              1.665145e+06
8   2024    9      2.127379e+08              1.680485e+06
9   2024   10      2.200000e+08              1.695825e+06
10  2024   11      2.272621e+08              1.711165e+06
11  2024   12      2.345242e+08              1.726505e+06
0   2025    1      1.682679e+08              1.636969e+06
1   2025    2      1.755300e+08              1.652309e+06
2   2025    3      1.827921e+08              1.667649e+06
3   2025    4      1.900542e+08              1.682989e+06
4   2025    5      1.973164e+08              1.698329e+06
5   2025    6      2.045785e+08              1.713669e+06
6   2025    7      2.118406e+08              1.729009e+06
7   2025    8      2.191027e+08              1.744349e+06
8   2025    9      2.263648e+08              1.759689e+06
9   2025   10      2.336269e+08              1.775030e+06
10  2025   11      2.408890e+08              1.790370e+06
11  2025   12      2.481511e+08              1.805710e+06
0   2026    1      1.818948e+08              1.716174e+06
1   2026    2      1.891569e+08              1.731514e+06
2   2026    3      1.964190e+08              1.746854e+06
3   2026    4      2.036811e+08              1.762194e+06
4   2026    5      2.109432e+08              1.777534e+06
5   2026    6      2.182053e+08              1.792874e+06
6   2026    7      2.254674e+08              1.808214e+06
7   2026    8      2.327296e+08              1.823554e+06
8   2026    9      2.399917e+08              1.838894e+06
9   2026   10      2.472538e+08              1.854234e+06
10  2026   11      2.545159e+08              1.869574e+06
11  2026   12      2.617780e+08              1.884914e+06

In [61]:
# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2023 (agosto a diciembre)
fechas_2023_faltantes = pd.DataFrame({'año': np.repeat(2023, 5),
                                      'mes': range(8, 13)})

# Realizar predicciones con el modelo de montos para 2023 (agosto a diciembre)
predicciones_montos_2023 = modelo_montos.predict(fechas_2023_faltantes[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2023 (agosto a diciembre)
predicciones_promedio_2023 = modelo_promedio.predict(fechas_2023_faltantes[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2023 (agosto a diciembre)
fechas_2023_faltantes['montos_predichos'] = predicciones_montos_2023
fechas_2023_faltantes['promedio_montos_predicho'] = predicciones_promedio_2023

# Filtrar las filas de fechas_2024_2026 que no corresponden a los meses de agosto a diciembre de 2023
fechas_2024_2026_filtradas = fechas_2024_2026[fechas_2024_2026['año'] != 2023]

# Concatenar los DataFrames para obtener el resultado final
nuevas_fechas = pd.concat([fechas_2023_faltantes, fechas_2024_2026_filtradas])

nuevas_fechas

     año  mes  montos_predichos  promedio_montos_predicho
0   2023    8      1.918489e+08              1.585940e+06
1   2023    9      1.991110e+08              1.601280e+06
2   2023   10      2.063731e+08              1.616620e+06
3   2023   11      2.136352e+08              1.631960e+06
4   2023   12      2.208974e+08              1.647300e+06
0   2024    1               NaN                       NaN
1   2024    2               NaN                       NaN
2   2024    3               NaN                       NaN
3   2024    4               NaN                       NaN
4   2024    5               NaN                       NaN
5   2024    6               NaN                       NaN
6   2024    7               NaN                       NaN
7   2024    8               NaN                       NaN
8   2024    9               NaN                       NaN
9   2024   10               NaN                       NaN
10  2024   11               NaN                       NaN
11  2024   12               NaN                       NaN
12  2025    1               NaN                       NaN
13  2025    2               NaN                       NaN
14  2025    3               NaN                       NaN
15  2025    4               NaN                       NaN
16  2025    5               NaN                       NaN
17  2025    6               NaN                       NaN
18  2025    7               NaN                       NaN
19  2025    8               NaN                       NaN
20  2025    9               NaN                       NaN
21  2025   10               NaN                       NaN
22  2025   11               NaN                       NaN
23  2025   12               NaN                       NaN
24  2026    1               NaN                       NaN
25  2026    2               NaN                       NaN
26  2026    3               NaN                       NaN
27  2026    4               NaN                       NaN
28  2026    5               NaN                       NaN
29  2026    6               NaN                       NaN
30  2026    7               NaN                       NaN
31  2026    8               NaN                       NaN
32  2026    9               NaN                       NaN
33  2026   10               NaN                       NaN
34  2026   11               NaN                       NaN
35  2026   12               NaN                       NaN

In [65]:
# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2023 (agosto a diciembre)
fechas_2023_faltantes = pd.DataFrame({'año': np.repeat(2023, 5),
                                      'mes': range(8, 13)})

# Realizar predicciones con el modelo de montos para 2023 (agosto a diciembre)
predicciones_montos_2023 = modelo_montos.predict(fechas_2023_faltantes[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2023 (agosto a diciembre)
predicciones_promedio_2023 = modelo_promedio.predict(fechas_2023_faltantes[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2023 (agosto a diciembre)
fechas_2023_faltantes['montos_predichos'] = predicciones_montos_2023
fechas_2023_faltantes['promedio_montos_predicho'] = predicciones_promedio_2023

# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                 'mes': np.tile(range(1, 13), 3)})

# Realizar predicciones con el modelo de montos para 2024-2026
predicciones_montos_2024_2026 = modelo_montos.predict(fechas_2024_2026[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2024-2026
predicciones_promedio_2024_2026 = modelo_promedio.predict(fechas_2024_2026[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2024-2026
fechas_2024_2026['montos_predichos'] = predicciones_montos_2024_2026
fechas_2024_2026['promedio_montos_predicho'] = predicciones_promedio_2024_2026

# Concatenar los DataFrames para obtener el resultado final
nuevas_fechas = pd.concat([fechas_2023_faltantes, fechas_2024_2026])
# Cambiar el nombre de las columnas
nuevas_fechas = nuevas_fechas.rename(columns={'montos_predichos': 'montos', 
                                              'promedio_montos_predicho': 'promedio_montos'})
nuevas_fechas

     año  mes        montos  promedio_montos
0   2023    8  1.918489e+08     1.585940e+06
1   2023    9  1.991110e+08     1.601280e+06
2   2023   10  2.063731e+08     1.616620e+06
3   2023   11  2.136352e+08     1.631960e+06
4   2023   12  2.208974e+08     1.647300e+06
0   2024    1  1.546410e+08     1.557764e+06
1   2024    2  1.619031e+08     1.573104e+06
2   2024    3  1.691653e+08     1.588444e+06
3   2024    4  1.764274e+08     1.603784e+06
4   2024    5  1.836895e+08     1.619124e+06
5   2024    6  1.909516e+08     1.634464e+06
6   2024    7  1.982137e+08     1.649804e+06
7   2024    8  2.054758e+08     1.665145e+06
8   2024    9  2.127379e+08     1.680485e+06
9   2024   10  2.200000e+08     1.695825e+06
10  2024   11  2.272621e+08     1.711165e+06
11  2024   12  2.345242e+08     1.726505e+06
12  2025    1  1.682679e+08     1.636969e+06
13  2025    2  1.755300e+08     1.652309e+06
14  2025    3  1.827921e+08     1.667649e+06
15  2025    4  1.900542e+08     1.682989e+06
16  2025    5  1.973164e+08     1.698329e+06
17  2025    6  2.045785e+08     1.713669e+06
18  2025    7  2.118406e+08     1.729009e+06
19  2025    8  2.191027e+08     1.744349e+06
20  2025    9  2.263648e+08     1.759689e+06
21  2025   10  2.336269e+08     1.775030e+06
22  2025   11  2.408890e+08     1.790370e+06
23  2025   12  2.481511e+08     1.805710e+06
24  2026    1  1.818948e+08     1.716174e+06
25  2026    2  1.891569e+08     1.731514e+06
26  2026    3  1.964190e+08     1.746854e+06
27  2026    4  2.036811e+08     1.762194e+06
28  2026    5  2.109432e+08     1.777534e+06
29  2026    6  2.182053e+08     1.792874e+06
30  2026    7  2.254674e+08     1.808214e+06
31  2026    8  2.327296e+08     1.823554e+06
32  2026    9  2.399917e+08     1.838894e+06
33  2026   10  2.472538e+08     1.854234e+06
34  2026   11  2.545159e+08     1.869574e+06
35  2026   12  2.617780e+08     1.884914e+06

In [69]:
total_promedios_pachuca = pd.concat([nuevas_fechas, promedio_creditos_pachuca], ignore_index=True)
total_promedios_pachuca

     año  mes        montos  promedio_montos
0   2023    8  1.918489e+08     1.585940e+06
1   2023    9  1.991110e+08     1.601280e+06
2   2023   10  2.063731e+08     1.616620e+06
3   2023   11  2.136352e+08     1.631960e+06
4   2023   12  2.208974e+08     1.647300e+06
..   ...  ...           ...              ...
91  2023    3  1.534318e+08     1.581771e+06
92  2023    4  2.308201e+07     1.154100e+06
93  2023    5  1.766667e+08     1.218391e+06
94  2023    6  1.870118e+08     1.289736e+06
95  2023    7  1.525440e+08     1.481010e+06

[96 rows x 4 columns]

In [70]:
total_promedios_pachuca = total_promedios_pachuca.groupby('año')['promedio_montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
total_promedios_pachuca['modalidad'] = 'Créditos (todos)'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
# Formatear la columna 'montos' con la función personalizada
total_promedios_pachuca['promedio_montos'] = total_promedios_pachuca['promedio_montos'].map(format_number)

total_promedios_pachuca

    año promedio_montos         modalidad
0  2019   14,590,982.17  Créditos (todos)
1  2020   16,237,077.68  Créditos (todos)
2  2021   17,161,514.30  Créditos (todos)
3  2022   18,825,452.94  Créditos (todos)
4  2023   17,571,132.38  Créditos (todos)
5  2024   19,705,613.30  Créditos (todos)
6  2025   20,656,071.60  Créditos (todos)
7  2026   21,606,529.90  Créditos (todos)

## Vivienda nueva: promedio

In [88]:
# Filtrar los datos por la modalidad '1'
creditos_2019_modalidad_1 = creditos_2019_pachuca[creditos_2019_pachuca['modalidad'] == 1]
# Calcular la suma y el número de créditos por mes
promedio_creditos_2019_modalidad_1 = creditos_2019_modalidad_1.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()
# Renombrar las columnas
promedio_creditos_2019_modalidad_1.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)
# Calcular el promedio de montos por mes
promedio_creditos_2019_modalidad_1['promedio_montos'] = promedio_creditos_2019_modalidad_1['montos'] / promedio_creditos_2019_modalidad_1['num_creditos']
# Asignar el valor del año 2019 a una nueva columna llamada 'año'
promedio_creditos_2019_modalidad_1['año'] = 2019
# Seleccionar las columnas relevantes
promedio_creditos_2019_modalidad_1 = promedio_creditos_2019_modalidad_1[['año', 'mes', 'montos', 'promedio_montos']]

promedio_creditos_2019_modalidad_1

     año  mes        montos  promedio_montos
0   2019    1  7.955017e+07     1.591003e+06
1   2019    2  6.865934e+07     1.401211e+06
2   2019    3  7.813391e+07     1.562678e+06
3   2019    4  6.500411e+07     1.710635e+06
4   2019    5  7.042122e+07     1.600482e+06
5   2019    6  8.746573e+07     1.650297e+06
6   2019    7  8.074711e+07     1.614942e+06
7   2019    8  1.045717e+08     1.802961e+06
8   2019    9  9.784357e+07     1.778974e+06
9   2019   10  7.894973e+07     1.644786e+06
10  2019   11  9.374840e+07     1.488070e+06
11  2019   12  1.256562e+08     2.026713e+06

In [75]:
# Función para calcular totales y promedios
def calcular_promedio_creditos(df, año):
    # Filtrar los datos por la modalidad '1'
    df_modalidad_1 = df[df['modalidad'] == 1]
    
    # Calcular la suma y el número de créditos por mes
    promedio_creditos = df_modalidad_1.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()

    # Renombrar las columnas
    promedio_creditos.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)

    # Calcular el promedio de montos por mes
    promedio_creditos['promedio_montos'] = promedio_creditos['montos'] / promedio_creditos['num_creditos']

    # Asignar el valor del año
    promedio_creditos['año'] = año

    # Seleccionar las columnas relevantes
    promedio_creditos = promedio_creditos[['año', 'mes', 'montos', 'promedio_montos']]

    return promedio_creditos

# Calcular totales y promedios para el año 2019
promedio_creditos_2019 = calcular_promedio_creditos(creditos_2019_pachuca, 2019)

# Calcular totales y promedios para el año 2020
promedio_creditos_2020 = calcular_promedio_creditos(creditos_2020_pachuca, 2020)

# Calcular totales y promedios para el año 2021
promedio_creditos_2021 = calcular_promedio_creditos(creditos_2021_pachuca, 2021)

# Calcular totales y promedios para el año 2022
promedio_creditos_2022 = calcular_promedio_creditos(creditos_2022_pachuca, 2022)

# Calcular totales y promedios para el año 2023
promedio_creditos_2023 = calcular_promedio_creditos(creditos_2023_pachuca, 2023)
# Concatenar los DataFrames de promedio de créditos de cada año
promedio_creditos_nueva_pachuca = pd.concat([promedio_creditos_2019, promedio_creditos_2020, 
                                             promedio_creditos_2021, promedio_creditos_2022, 
                                             promedio_creditos_2023], ignore_index=True)
promedio_creditos_nueva_pachuca

     año  mes        montos  promedio_montos
0   2019    1  7.955017e+07     1.591003e+06
1   2019    2  6.865934e+07     1.401211e+06
2   2019    3  7.813391e+07     1.562678e+06
3   2019    4  6.500411e+07     1.710635e+06
4   2019    5  7.042122e+07     1.600482e+06
5   2019    6  8.746573e+07     1.650297e+06
6   2019    7  8.074711e+07     1.614942e+06
7   2019    8  1.045717e+08     1.802961e+06
8   2019    9  9.784357e+07     1.778974e+06
9   2019   10  7.894973e+07     1.644786e+06
10  2019   11  9.374840e+07     1.488070e+06
11  2019   12  1.256562e+08     2.026713e+06
12  2020    1  8.963171e+07     1.991816e+06
13  2020    2  7.330905e+07     1.666115e+06
14  2020    3  8.646081e+07     1.490704e+06
15  2020    4  4.686170e+07     1.802373e+06
16  2020    5  6.383653e+07     1.484571e+06
17  2020    6  8.994808e+07     1.729771e+06
18  2020    7  8.193729e+07     1.437496e+06
19  2020    8  9.771782e+07     1.809589e+06
20  2020    9  1.195538e+08     1.513340e+06
21  2020   10  8.715167e+07     1.815660e+06
22  2020   11  9.714141e+07     1.832857e+06
23  2020   12  1.463205e+08     2.090292e+06
24  2021    1  8.609399e+07     1.757020e+06
25  2021    2  1.021271e+08     1.674215e+06
26  2021    3  1.310891e+08     1.747855e+06
27  2021    4  8.282697e+07     1.562773e+06
28  2021    5  1.089669e+08     2.055978e+06
29  2021    6  7.237658e+07     1.315938e+06
30  2021    7  1.311713e+08     1.873876e+06
31  2021    8  7.860909e+07     1.483190e+06
32  2021    9  1.082944e+08     1.933829e+06
33  2021   10  8.828650e+07     1.605209e+06
34  2021   11  8.905610e+07     1.817471e+06
35  2021   12  1.456424e+08     2.080605e+06
36  2022    1  8.764514e+07     1.537634e+06
37  2022    2  6.452677e+07     1.654533e+06
38  2022    3  8.516246e+07     1.548408e+06
39  2022    4  8.968359e+07     1.758502e+06
40  2022    5  9.198135e+07     2.139101e+06
41  2022    6  9.583941e+07     2.129765e+06
42  2022    7  1.147764e+08     2.165593e+06
43  2022    8  1.008748e+08     2.101558e+06
44  2022    9  1.191839e+08     2.054895e+06
45  2022   10  9.823773e+07     2.338994e+06
46  2022   11  1.433523e+08     2.205420e+06
47  2022   12  1.161401e+08     1.707943e+06
48  2023    1  8.323639e+07     2.080910e+06
49  2023    2  3.826531e+07     1.663709e+06
50  2023    3  5.808575e+07     1.873734e+06
51  2023    4  4.024524e+06     8.049047e+05
52  2023    5  1.039947e+08     1.704830e+06
53  2023    6  1.048520e+08     1.664317e+06
54  2023    7  8.783359e+07     2.142283e+06

### *MODELO REGRESIÓN PARA DATOS HASTA 2026, MODALIDAD 1: NUEVA*

In [76]:
X_montos = promedio_creditos_nueva_pachuca[['año', 'mes']]
y_montos = promedio_creditos_nueva_pachuca['montos']
# Datos en conjuntos de entrenamiento y prueba
X_train_montos, X_test_montos, y_train_montos, y_test_montos = train_test_split(X_montos, y_montos, test_size=0.2, random_state=42)
# Modelo de montos
modelo_montos = LinearRegression()
modelo_montos.fit(X_train_montos, y_train_montos)

LinearRegression()

In [77]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Hacer predicciones en el conjunto de prueba para el modelo de montos
y_pred_montos = modelo_montos.predict(X_test_montos)
# Calcular el coeficiente de determinación (R^2) para el modelo de montos
r2_montos = r2_score(y_test_montos, y_pred_montos)
print("Coeficiente de determinación (R^2) para el modelo de montos:", r2_montos)
# Calcular el error cuadrático medio (MSE) para el modelo de montos
mse_montos = mean_squared_error(y_test_montos, y_pred_montos)
print("Error cuadrático medio (MSE) para el modelo de montos:", mse_montos)
# Calcular el error absoluto medio (MAE) para el modelo de montos
mae_montos = mean_absolute_error(y_test_montos, y_pred_montos)
print("Error absoluto medio (MAE) para el modelo de montos:", mae_montos)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de montos
rmse_montos = np.sqrt(mse_montos)
print("Raíz del error cuadrático medio (RMSE) para el modelo de montos:", rmse_montos)

Coeficiente de determinación (R^2) para el modelo de montos: -0.01703058558648607
Error cuadrático medio (MSE) para el modelo de montos: 508649519469343.44
Error absoluto medio (MAE) para el modelo de montos: 14959219.968036445
Raíz del error cuadrático medio (RMSE) para el modelo de montos: 22553259.619605843

In [78]:
# Preparar datos para el modelo de promedio
X_promedio = promedio_creditos_nueva_pachuca[['año', 'mes']]
y_promedio = promedio_creditos_nueva_pachuca['promedio_montos']
# Dividir los datos de promedio en conjuntos de entrenamiento y prueba
X_train_promedio, X_test_promedio, y_train_promedio, y_test_promedio = train_test_split(X_promedio, y_promedio, test_size=0.2, random_state=42)
# Entrenar modelo de promedio
modelo_promedio = LinearRegression()
modelo_promedio.fit(X_train_promedio, y_train_promedio)

LinearRegression()

In [79]:
# Predicciones en el conjunto de prueba para el modelo de promedio
y_pred_promedio = modelo_promedio.predict(X_test_promedio)
# Calcular el coeficiente de determinación (R^2) para el modelo de promedio
r2_promedio = r2_score(y_test_promedio, y_pred_promedio)
print("Coeficiente de determinación (R^2) para el modelo de promedio:", r2_promedio)
# Calcular el error cuadrático medio (MSE) para el modelo de promedio
mse_promedio = mean_squared_error(y_test_promedio, y_pred_promedio)
print("Error cuadrático medio (MSE) para el modelo de promedio:", mse_promedio)
# Calcular el error absoluto medio (MAE) para el modelo de promedio
mae_promedio = mean_absolute_error(y_test_promedio, y_pred_promedio)
print("Error absoluto medio (MAE) para el modelo de promedio:", mae_promedio)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de promedio
rmse_promedio = np.sqrt(mse_promedio)
print("Raíz del error cuadrático medio (RMSE) para el modelo de promedio:", rmse_promedio)

Coeficiente de determinación (R^2) para el modelo de promedio: -0.2638513774346838
Error cuadrático medio (MSE) para el modelo de promedio: 48820750028.3337
Error absoluto medio (MAE) para el modelo de promedio: 175543.1684369562
Raíz del error cuadrático medio (RMSE) para el modelo de promedio: 220954.18083470088

In [80]:
# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2023 (agosto a diciembre)
fechas_2023_faltantes = pd.DataFrame({'año': np.repeat(2023, 5),
                                      'mes': range(8, 13)})

# Realizar predicciones con el modelo de montos para 2023 (agosto a diciembre)
predicciones_montos_2023 = modelo_montos.predict(fechas_2023_faltantes[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2023 (agosto a diciembre)
predicciones_promedio_2023 = modelo_promedio.predict(fechas_2023_faltantes[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2023 (agosto a diciembre)
fechas_2023_faltantes['montos_predichos'] = predicciones_montos_2023
fechas_2023_faltantes['promedio_montos_predicho'] = predicciones_promedio_2023

# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                 'mes': np.tile(range(1, 13), 3)})

# Realizar predicciones con el modelo de montos para 2024-2026
predicciones_montos_2024_2026 = modelo_montos.predict(fechas_2024_2026[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2024-2026
predicciones_promedio_2024_2026 = modelo_promedio.predict(fechas_2024_2026[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2024-2026
fechas_2024_2026['montos_predichos'] = predicciones_montos_2024_2026
fechas_2024_2026['promedio_montos_predicho'] = predicciones_promedio_2024_2026

# Concatenar los DataFrames para obtener el resultado final
nuevas_fechas_promedio = pd.concat([fechas_2023_faltantes, fechas_2024_2026])
# Cambiar el nombre de las columnas
nuevas_fechas_promedio = nuevas_fechas_promedio.rename(columns={'montos_predichos': 'montos', 
                                              'promedio_montos_predicho': 'promedio_montos'})
nuevas_fechas_promedio

     año  mes        montos  promedio_montos
0   2023    8  1.021814e+08     1.935878e+06
1   2023    9  1.065898e+08     1.968190e+06
2   2023   10  1.109982e+08     2.000502e+06
3   2023   11  1.154066e+08     2.032814e+06
4   2023   12  1.198150e+08     2.065126e+06
0   2024    1  7.303618e+07     1.771077e+06
1   2024    2  7.744456e+07     1.803389e+06
2   2024    3  8.185295e+07     1.835701e+06
3   2024    4  8.626133e+07     1.868013e+06
4   2024    5  9.066971e+07     1.900325e+06
5   2024    6  9.507809e+07     1.932637e+06
6   2024    7  9.948648e+07     1.964949e+06
7   2024    8  1.038949e+08     1.997261e+06
8   2024    9  1.083032e+08     2.029573e+06
9   2024   10  1.127116e+08     2.061885e+06
10  2024   11  1.171200e+08     2.094197e+06
11  2024   12  1.215284e+08     2.126509e+06
12  2025    1  7.474961e+07     1.832461e+06
13  2025    2  7.915799e+07     1.864773e+06
14  2025    3  8.356637e+07     1.897085e+06
15  2025    4  8.797475e+07     1.929397e+06
16  2025    5  9.238314e+07     1.961709e+06
17  2025    6  9.679152e+07     1.994021e+06
18  2025    7  1.011999e+08     2.026333e+06
19  2025    8  1.056083e+08     2.058645e+06
20  2025    9  1.100167e+08     2.090957e+06
21  2025   10  1.144250e+08     2.123269e+06
22  2025   11  1.188334e+08     2.155581e+06
23  2025   12  1.232418e+08     2.187893e+06
24  2026    1  7.646303e+07     1.893845e+06
25  2026    2  8.087142e+07     1.926157e+06
26  2026    3  8.527980e+07     1.958469e+06
27  2026    4  8.968818e+07     1.990781e+06
28  2026    5  9.409656e+07     2.023093e+06
29  2026    6  9.850494e+07     2.055405e+06
30  2026    7  1.029133e+08     2.087717e+06
31  2026    8  1.073217e+08     2.120029e+06
32  2026    9  1.117301e+08     2.152341e+06
33  2026   10  1.161385e+08     2.184653e+06
34  2026   11  1.205469e+08     2.216965e+06
35  2026   12  1.249552e+08     2.249277e+06

In [84]:
nueva_promedios_pachuca = pd.concat([nuevas_fechas_promedio, promedio_creditos_nueva_pachuca], ignore_index=True)
nueva_promedios_pachuca

     año  mes        montos  promedio_montos
0   2023    8  1.021814e+08     1.935878e+06
1   2023    9  1.065898e+08     1.968190e+06
2   2023   10  1.109982e+08     2.000502e+06
3   2023   11  1.154066e+08     2.032814e+06
4   2023   12  1.198150e+08     2.065126e+06
..   ...  ...           ...              ...
91  2023    3  5.808575e+07     1.873734e+06
92  2023    4  4.024524e+06     8.049047e+05
93  2023    5  1.039947e+08     1.704830e+06
94  2023    6  1.048520e+08     1.664317e+06
95  2023    7  8.783359e+07     2.142283e+06

[96 rows x 4 columns]

In [85]:
nueva_promedios_pachuca = nueva_promedios_pachuca.groupby('año')['promedio_montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
nueva_promedios_pachuca['modalidad'] = 'Nueva'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
# Formatear la columna 'montos' con la función personalizada
nueva_promedios_pachuca['promedio_montos'] = nueva_promedios_pachuca['promedio_montos'].map(format_number)

nueva_promedios_pachuca

    año promedio_montos modalidad
0  2019   19,872,752.86     Nueva
1  2020   20,664,582.78     Nueva
2  2021   20,907,961.24     Nueva
3  2022   23,342,344.52     Nueva
4  2023   21,937,195.86     Nueva
5  2024   23,385,520.89     Nueva
6  2025   24,122,126.73     Nueva
7  2026   24,858,732.58     Nueva

## Vivienda Usada: promedio

In [100]:
# Función para calcular totales y promedios
def calcular_promedio_creditos(df, año):
    # Filtrar los datos por la modalidad '3'
    df_modalidad_1 = df[df['modalidad'] == 3]
    
    # Calcular la suma y el número de créditos por mes
    promedio_creditos = df_modalidad_1.groupby('mes')['monto'].agg(['sum', 'count']).reset_index()

    # Renombrar las columnas
    promedio_creditos.rename(columns={'sum': 'montos', 'count': 'num_creditos'}, inplace=True)

    # Calcular el promedio de montos por mes
    promedio_creditos['promedio_montos'] = promedio_creditos['montos'] / promedio_creditos['num_creditos']

    # Asignar el valor del año
    promedio_creditos['año'] = año

    # Seleccionar las columnas relevantes
    promedio_creditos = promedio_creditos[['año', 'mes', 'montos', 'promedio_montos']]

    return promedio_creditos

# Calcular totales y promedios para el año 2019
promedio_creditos_2019 = calcular_promedio_creditos(creditos_2019_pachuca, 2019)

# Calcular totales y promedios para el año 2020
promedio_creditos_2020 = calcular_promedio_creditos(creditos_2020_pachuca, 2020)

# Calcular totales y promedios para el año 2021
promedio_creditos_2021 = calcular_promedio_creditos(creditos_2021_pachuca, 2021)

# Calcular totales y promedios para el año 2022
promedio_creditos_2022 = calcular_promedio_creditos(creditos_2022_pachuca, 2022)

# Calcular totales y promedios para el año 2023
promedio_creditos_2023 = calcular_promedio_creditos(creditos_2023_pachuca, 2023)
# Concatenar los DataFrames de promedio de créditos de cada año
promedio_creditos_usada_pachuca = pd.concat([promedio_creditos_2019, promedio_creditos_2020, 
                                             promedio_creditos_2021, promedio_creditos_2022, 
                                             promedio_creditos_2023], ignore_index=True)
promedio_creditos_usada_pachuca

     año  mes        montos  promedio_montos
0   2019    1  1.839433e+07     9.681225e+05
1   2019    2  2.851903e+07     9.506344e+05
2   2019    3  2.772768e+07     9.242560e+05
3   2019    4  2.730303e+07     8.532196e+05
4   2019    5  3.809934e+07     7.470459e+05
5   2019    6  3.038951e+07     7.792181e+05
6   2019    7  2.959400e+07     8.220555e+05
7   2019    8  3.174622e+07     9.337123e+05
8   2019    9  3.115727e+07     8.654798e+05
9   2019   10  4.019544e+07     7.729893e+05
10  2019   11  2.894311e+07     7.421311e+05
11  2019   12  4.719615e+07     8.427883e+05
12  2020    1  3.038381e+07     9.801230e+05
13  2020    2  2.583166e+07     8.610552e+05
14  2020    3  2.246318e+07     8.022565e+05
15  2020    4  1.191588e+07     9.929904e+05
16  2020    5  2.246991e+07     9.362462e+05
17  2020    6  2.319721e+07     7.732404e+05
18  2020    7  3.037659e+07     9.798901e+05
19  2020    8  3.861987e+07     1.287329e+06
20  2020    9  4.097241e+07     1.170640e+06
21  2020   10  5.816727e+07     1.292606e+06
22  2020   11  7.180383e+07     1.595641e+06
23  2020   12  4.106672e+07     9.333345e+05
24  2021    1  2.866589e+07     1.246343e+06
25  2021    2  3.440232e+07     9.829234e+05
26  2021    3  5.574588e+07     1.211867e+06
27  2021    4  5.895696e+07     1.034333e+06
28  2021    5  4.591160e+07     1.020258e+06
29  2021    6  7.798654e+07     1.321806e+06
30  2021    7  8.067881e+07     1.344647e+06
31  2021    8  4.369339e+07     1.040319e+06
32  2021    9  5.384642e+07     1.252242e+06
33  2021   10  3.253771e+07     9.859911e+05
34  2021   11  5.239872e+07     1.247589e+06
35  2021   12  6.338392e+07     1.267678e+06
36  2022    1  5.160283e+07     1.984724e+06
37  2022    2  4.412415e+07     1.297769e+06
38  2022    3  8.809292e+07     1.631350e+06
39  2022    4  5.859451e+07     1.273794e+06
40  2022    5  6.845188e+07     1.755176e+06
41  2022    6  5.896624e+07     1.403958e+06
42  2022    7  8.418067e+07     1.618859e+06
43  2022    8  3.885549e+07     1.253403e+06
44  2022    9  9.549629e+07     1.989506e+06
45  2022   10  5.526082e+07     1.347825e+06
46  2022   11  5.866558e+07     1.725458e+06
47  2022   12  1.361032e+08     1.944331e+06
48  2023    1  3.635255e+07     1.580545e+06
49  2023    2  6.380408e+07     1.595102e+06
50  2023    3  7.204642e+07     1.895958e+06
51  2023    4  1.903048e+07     1.463883e+06
52  2023    5  5.839109e+07     1.191655e+06
53  2023    6  6.923265e+07     1.331397e+06
54  2023    7  5.589373e+07     1.397343e+06

### *MODELO REGRESIÓN PARA DATOS HASTA 2026, MODALIDAD 1: NUEVA*

In [101]:
X_montos = promedio_creditos_usada_pachuca[['año', 'mes']]
y_montos = promedio_creditos_usada_pachuca['montos']
# Datos en conjuntos de entrenamiento y prueba
X_train_montos, X_test_montos, y_train_montos, y_test_montos = train_test_split(X_montos, y_montos, test_size=0.2, random_state=42)
# Modelo de montos
modelo_montos = LinearRegression()
modelo_montos.fit(X_train_montos, y_train_montos)

LinearRegression()

In [102]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import numpy as np

# Hacer predicciones en el conjunto de prueba para el modelo de montos
y_pred_montos = modelo_montos.predict(X_test_montos)
# Calcular el coeficiente de determinación (R^2) para el modelo de montos
r2_montos = r2_score(y_test_montos, y_pred_montos)
print("Coeficiente de determinación (R^2) para el modelo de montos:", r2_montos)
# Calcular el error cuadrático medio (MSE) para el modelo de montos
mse_montos = mean_squared_error(y_test_montos, y_pred_montos)
print("Error cuadrático medio (MSE) para el modelo de montos:", mse_montos)
# Calcular el error absoluto medio (MAE) para el modelo de montos
mae_montos = mean_absolute_error(y_test_montos, y_pred_montos)
print("Error absoluto medio (MAE) para el modelo de montos:", mae_montos)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de montos
rmse_montos = np.sqrt(mse_montos)
print("Raíz del error cuadrático medio (RMSE) para el modelo de montos:", rmse_montos)

Coeficiente de determinación (R^2) para el modelo de montos: 0.23282011825675786
Error cuadrático medio (MSE) para el modelo de montos: 125208338348372.6
Error absoluto medio (MAE) para el modelo de montos: 8364801.243545852
Raíz del error cuadrático medio (RMSE) para el modelo de montos: 11189653.182667129

In [103]:
# Preparar datos para el modelo de promedio
X_promedio = promedio_creditos_usada_pachuca[['año', 'mes']]
y_promedio = promedio_creditos_usada_pachuca['promedio_montos']
# Dividir los datos de promedio en conjuntos de entrenamiento y prueba
X_train_promedio, X_test_promedio, y_train_promedio, y_test_promedio = train_test_split(X_promedio, y_promedio, test_size=0.2, random_state=42)
# Entrenar modelo de promedio
modelo_promedio = LinearRegression()
modelo_promedio.fit(X_train_promedio, y_train_promedio)

LinearRegression()

In [104]:
# Predicciones en el conjunto de prueba para el modelo de promedio
y_pred_promedio = modelo_promedio.predict(X_test_promedio)
# Calcular el coeficiente de determinación (R^2) para el modelo de promedio
r2_promedio = r2_score(y_test_promedio, y_pred_promedio)
print("Coeficiente de determinación (R^2) para el modelo de promedio:", r2_promedio)
# Calcular el error cuadrático medio (MSE) para el modelo de promedio
mse_promedio = mean_squared_error(y_test_promedio, y_pred_promedio)
print("Error cuadrático medio (MSE) para el modelo de promedio:", mse_promedio)
# Calcular el error absoluto medio (MAE) para el modelo de promedio
mae_promedio = mean_absolute_error(y_test_promedio, y_pred_promedio)
print("Error absoluto medio (MAE) para el modelo de promedio:", mae_promedio)
# Calcular la raíz del error cuadrático medio (RMSE) para el modelo de promedio
rmse_promedio = np.sqrt(mse_promedio)
print("Raíz del error cuadrático medio (RMSE) para el modelo de promedio:", rmse_promedio)

Coeficiente de determinación (R^2) para el modelo de promedio: 0.19442367313481235
Error cuadrático medio (MSE) para el modelo de promedio: 41462761332.36567
Error absoluto medio (MAE) para el modelo de promedio: 148315.36380126883
Raíz del error cuadrático medio (RMSE) para el modelo de promedio: 203624.06864701843

In [105]:
# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2023 (agosto a diciembre)
fechas_2023_faltantes = pd.DataFrame({'año': np.repeat(2023, 5),
                                      'mes': range(8, 13)})

# Realizar predicciones con el modelo de montos para 2023 (agosto a diciembre)
predicciones_montos_2023 = modelo_montos.predict(fechas_2023_faltantes[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2023 (agosto a diciembre)
predicciones_promedio_2023 = modelo_promedio.predict(fechas_2023_faltantes[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2023 (agosto a diciembre)
fechas_2023_faltantes['montos_predichos'] = predicciones_montos_2023
fechas_2023_faltantes['promedio_montos_predicho'] = predicciones_promedio_2023

# Crear un DataFrame con todas las combinaciones posibles de año y mes para 2024-2026
fechas_2024_2026 = pd.DataFrame({'año': np.repeat(range(2024, 2027), 12),
                                 'mes': np.tile(range(1, 13), 3)})

# Realizar predicciones con el modelo de montos para 2024-2026
predicciones_montos_2024_2026 = modelo_montos.predict(fechas_2024_2026[['año', 'mes']])

# Realizar predicciones con el modelo de promedio para 2024-2026
predicciones_promedio_2024_2026 = modelo_promedio.predict(fechas_2024_2026[['año', 'mes']])

# Agregar las predicciones al DataFrame de fechas para 2024-2026
fechas_2024_2026['montos_predichos'] = predicciones_montos_2024_2026
fechas_2024_2026['promedio_montos_predicho'] = predicciones_promedio_2024_2026

# Concatenar los DataFrames para obtener el resultado final
usadas_fechas_promedio = pd.concat([fechas_2023_faltantes, fechas_2024_2026])
# Cambiar el nombre de las columnas
usadas_fechas_promedio = usadas_fechas_promedio.rename(columns={'montos_predichos': 'montos', 
                                              'promedio_montos_predicho': 'promedio_montos'})
usadas_fechas_promedio

     año  mes        montos  promedio_montos
0   2023    8  7.751189e+07     1.724421e+06
1   2023    9  8.047184e+07     1.736284e+06
2   2023   10  8.343178e+07     1.748147e+06
3   2023   11  8.639173e+07     1.760011e+06
4   2023   12  8.935167e+07     1.771874e+06
0   2024    1  6.753942e+07     1.858098e+06
1   2024    2  7.049936e+07     1.869961e+06
2   2024    3  7.345931e+07     1.881825e+06
3   2024    4  7.641925e+07     1.893688e+06
4   2024    5  7.937920e+07     1.905551e+06
5   2024    6  8.233914e+07     1.917415e+06
6   2024    7  8.529909e+07     1.929278e+06
7   2024    8  8.825903e+07     1.941141e+06
8   2024    9  9.121898e+07     1.953004e+06
9   2024   10  9.417893e+07     1.964868e+06
10  2024   11  9.713887e+07     1.976731e+06
11  2024   12  1.000988e+08     1.988594e+06
12  2025    1  7.828656e+07     2.074818e+06
13  2025    2  8.124650e+07     2.086682e+06
14  2025    3  8.420645e+07     2.098545e+06
15  2025    4  8.716640e+07     2.110408e+06
16  2025    5  9.012634e+07     2.122272e+06
17  2025    6  9.308629e+07     2.134135e+06
18  2025    7  9.604623e+07     2.145998e+06
19  2025    8  9.900618e+07     2.157862e+06
20  2025    9  1.019661e+08     2.169725e+06
21  2025   10  1.049261e+08     2.181588e+06
22  2025   11  1.078860e+08     2.193451e+06
23  2025   12  1.108460e+08     2.205315e+06
24  2026    1  8.903370e+07     2.291539e+06
25  2026    2  9.199365e+07     2.303402e+06
26  2026    3  9.495359e+07     2.315265e+06
27  2026    4  9.791354e+07     2.327129e+06
28  2026    5  1.008735e+08     2.338992e+06
29  2026    6  1.038334e+08     2.350855e+06
30  2026    7  1.067934e+08     2.362719e+06
31  2026    8  1.097533e+08     2.374582e+06
32  2026    9  1.127133e+08     2.386445e+06
33  2026   10  1.156732e+08     2.398309e+06
34  2026   11  1.186332e+08     2.410172e+06
35  2026   12  1.215931e+08     2.422035e+06

In [108]:
usada_promedios_pachuca = pd.concat([usadas_fechas_promedio, promedio_creditos_usada_pachuca], ignore_index=True)
usada_promedios_pachuca

     año  mes        montos  promedio_montos
0   2023    8  7.751189e+07     1.724421e+06
1   2023    9  8.047184e+07     1.736284e+06
2   2023   10  8.343178e+07     1.748147e+06
3   2023   11  8.639173e+07     1.760011e+06
4   2023   12  8.935167e+07     1.771874e+06
..   ...  ...           ...              ...
91  2023    3  7.204642e+07     1.895958e+06
92  2023    4  1.903048e+07     1.463883e+06
93  2023    5  5.839109e+07     1.191655e+06
94  2023    6  6.923265e+07     1.331397e+06
95  2023    7  5.589373e+07     1.397343e+06

[96 rows x 4 columns]

In [109]:
usada_promedios_pachuca = usada_promedios_pachuca.groupby('año')['promedio_montos'].sum().reset_index()
# Agregar una nueva columna 'vivienda' con el valor 'Usada'
usada_promedios_pachuca['modalidad'] = 'Usada'
# Función para formatear números con separadores de coma y dos decimales
def format_number(x):
   return '{:,.2f}'.format(x)
# Formatear la columna 'montos' con la función personalizada
usada_promedios_pachuca['promedio_montos'] = usada_promedios_pachuca['promedio_montos'].map(format_number)

usada_promedios_pachuca

    año promedio_montos modalidad
0  2019   10,201,652.88     Usada
1  2020   12,605,352.22     Usada
2  2021   13,955,995.96     Usada
3  2022   19,226,154.07     Usada
4  2023   19,196,621.48     Usada
5  2024   23,080,154.58     Usada
6  2025   25,680,798.97     Usada
7  2026   28,281,443.36     Usada

In [110]:
forecast_creditosgral_promedios_pachuca = pd.concat([
    total_promedios_pachuca,
    nueva_promedios_pachuca,
    usada_promedios_pachuca], ignore_index=True)
forecast_creditosgral_promedios_pachuca

     año promedio_montos         modalidad
0   2019   14,590,982.17  Créditos (todos)
1   2020   16,237,077.68  Créditos (todos)
2   2021   17,161,514.30  Créditos (todos)
3   2022   18,825,452.94  Créditos (todos)
4   2023   17,571,132.38  Créditos (todos)
5   2024   19,705,613.30  Créditos (todos)
6   2025   20,656,071.60  Créditos (todos)
7   2026   21,606,529.90  Créditos (todos)
8   2019   19,872,752.86             Nueva
9   2020   20,664,582.78             Nueva
10  2021   20,907,961.24             Nueva
11  2022   23,342,344.52             Nueva
12  2023   21,937,195.86             Nueva
13  2024   23,385,520.89             Nueva
14  2025   24,122,126.73             Nueva
15  2026   24,858,732.58             Nueva
16  2019   10,201,652.88             Usada
17  2020   12,605,352.22             Usada
18  2021   13,955,995.96             Usada
19  2022   19,226,154.07             Usada
20  2023   19,196,621.48             Usada
21  2024   23,080,154.58             Usada
22  2025   25,680,798.97             Usada
23  2026   28,281,443.36             Usada

In [111]:
# Datos
trimestres = forecast_creditosgral_promedios_pachuca['año']
modalidades = forecast_creditosgral_promedios_pachuca['modalidad']
promedio_montos = forecast_creditosgral_promedios_pachuca['promedio_montos']

# Limpiar las cadenas de montos y convertirlas a números
promedios_limpios = [float(promedio_montos.replace(',', '')) for promedio_montos in promedio_montos]

fig = go.Figure()
# Agregar líneas para cada modalidad
for modalidad in modalidades.unique():
    df_modalidad = forecast_creditosgral_promedios_pachuca[forecast_creditosgral_promedios_pachuca['modalidad'] == modalidad]
    fig.add_trace(go.Scatter(
        x=df_modalidad['año'],
        y=df_modalidad['promedio_montos'].apply(lambda x: float(x.replace(',', ''))),  # Usar los montos limpios
        mode='markers+lines',
        name=modalidad
    ))

fig.update_layout(
    title='Monto promedio por crédito',
    yaxis=dict(gridcolor='#dddcda'),
    plot_bgcolor='rgba(0,0,0,0)',  # Color de fondo del gráfico
)

# Agregar etiquetas de texto a los puntos
for trace in fig.data:
    df_modalidad = forecast_creditosgral_promedios_pachuca[forecast_creditosgral_promedios_pachuca['modalidad'] == trace.name]
    for i, point in enumerate(trace.y):
        fig.add_annotation(
            x=trace.x[i], 
            y=point, 
            text=f'{df_modalidad.iloc[i]["promedio_montos"]}', 
            showarrow=False,
            font=dict(color='black', size=10),
            yshift=10
        )

# Exportar gráfica como archivo HTML
def guardar_grafico_como_html(fig, nombre_archivo, carpeta='graficas'):
    # Crear la carpeta si no existe
    if not os.path.exists(carpeta):
        os.makedirs(carpeta)
    
    # Gráfica como archivo HTML en la carpeta especificada
    pio.write_html(fig, f'{carpeta}/{nombre_archivo}.html')

guardar_grafico_como_html(fig, 'g_scatt_forecastcreditgral_promedio_pachuca', carpeta='graficas')
fig.show()